import type { LayerContext } from '../context.js';
import * as b from '../build.js';

// Point-of-interest icons. All share a common base style (the old `poi-*` rule); most add an
// icon `match` expression keyed on the relevant OSM tag. `highway` and `office` have no icon
// rule and are emitted with the base style only.

// Icon match expressions (verbatim from the v5/old rules table), keyed by POI category.
const IMAGES: Record<string, unknown> = {
	amenity: [
		'match',
		['get', 'amenity'],
		'arts_centre',
		'basics:icon-art_gallery',
		'atm',
		'basics:icon-atm',
		'bank',
		'basics:icon-bank',
		'bar',
		'basics:icon-bar',
		'bench',
		'basics:icon-bench',
		'bicycle_rental',
		'basics:icon-bicycle_share',
		'biergarten',
		'basics:icon-beergarden',
		'cafe',
		'basics:icon-cafe',
		'car_rental',
		'basics:icon-car_rental',
		'car_sharing',
		'basics:icon-car_rental',
		'car_wash',
		'basics:icon-car_wash',
		'cinema',
		'basics:icon-cinema',
		'college',
		'basics:icon-college',
		'community_centre',
		'basics:icon-community',
		'dentist',
		'basics:icon-dentist',
		'doctors',
		'basics:icon-doctor',
		'dog_park',
		'basics:icon-dog_park',
		'drinking_water',
		'basics:icon-drinking_water',
		'embassy',
		'basics:icon-embassy',
		'fast_food',
		'basics:icon-fast_food',
		'fire_station',
		'basics:icon-fire_station',
		'fountain',
		'basics:icon-fountain',
		'grave_yard',
		'basics:icon-cemetery',
		'hospital',
		'basics:icon-hospital',
		'hunting_stand',
		'basics:icon-huntingstand',
		'library',
		'basics:icon-library',
		'marketplace',
		'basics:icon-marketplace',
		'nightclub',
		'basics:icon-nightclub',
		'nursing_home',
		'basics:icon-nursinghome',
		'pharmacy',
		'basics:icon-pharmacy',
		'place_of_worship',
		'basics:icon-place_of_worship',
		'playground',
		'basics:icon-playground',
		'police',
		'basics:icon-police',
		'post_box',
		'basics:icon-postbox',
		'post_office',
		'basics:icon-post',
		'prison',
		'basics:icon-prison',
		'pub',
		'basics:icon-beer',
		'recycling',
		'basics:icon-recycling',
		'restaurant',
		'basics:icon-restaurant',
		'school',
		'basics:icon-school',
		'shelter',
		'basics:icon-shelter',
		'telephone',
		'basics:icon-telephone',
		'theatre',
		'basics:icon-theatre',
		'toilets',
		'basics:icon-toilet',
		'townhall',
		'basics:icon-town_hall',
		'vending_machine',
		'basics:icon-vendingmachine',
		'veterinary',
		'basics:icon-veterinary',
		'waste_basket',
		'basics:icon-waste_basket',
		'',
	],
	leisure: [
		'match',
		['get', 'leisure'],
		'golf_course',
		'basics:icon-golf',
		'ice_rink',
		'basics:icon-icerink',
		'pitch',
		'basics:icon-pitch',
		'stadium',
		'basics:icon-stadium',
		'swimming_pool',
		'basics:icon-swimming',
		'water_park',
		'basics:icon-waterpark',
		'basics:icon-sports',
	],
	tourism: [
		'match',
		['get', 'tourism'],
		'chalet',
		'basics:icon-chalet',
		'information',
		'basics:transport-information',
		'picnic_site',
		'basics:icon-picnic_site',
		'viewpoint',
		'basics:icon-viewpoint',
		'zoo',
		'basics:icon-zoo',
		'',
	],
	shop: [
		'match',
		['get', 'shop'],
		'alcohol',
		'basics:icon-alcohol_shop',
		'bakery',
		'basics:icon-bakery',
		'beauty',
		'basics:icon-beauty',
		'beverages',
		'basics:icon-beverages',
		'books',
		'basics:icon-books',
		'butcher',
		'basics:icon-butcher',
		'chemist',
		'basics:icon-chemist',
		'clothes',
		'basics:icon-clothes',
		'doityourself',
		'basics:icon-doityourself',
		'dry_cleaning',
		'basics:icon-drycleaning',
		'florist',
		'basics:icon-florist',
		'furniture',
		'basics:icon-furniture',
		'garden_centre',
		'basics:icon-garden_centre',
		'general',
		'basics:icon-shop',
		'gift',
		'basics:icon-gift',
		'greengrocer',
		'basics:icon-greengrocer',
		'hairdresser',
		'basics:icon-hairdresser',
		'hardware',
		'basics:icon-hardware',
		'jewelry',
		'basics:icon-jewelry_store',
		'kiosk',
		'basics:icon-kiosk',
		'laundry',
		'basics:icon-laundry',
		'newsagent',
		'basics:icon-newsagent',
		'optican',
		'basics:icon-optician',
		'outdoor',
		'basics:icon-outdoor',
		'shoes',
		'basics:icon-shoes',
		'sports',
		'basics:icon-sports',
		'stationery',
		'basics:icon-stationery',
		'toys',
		'basics:icon-toys',
		'travel_agency',
		'basics:icon-travel_agent',
		'video',
		'basics:icon-video',
		'basics:icon-shop',
	],
	man_made: [
		'match',
		['get', 'man_made'],
		'lighthouse',
		'basics:icon-lighthouse',
		'surveillance',
		'basics:icon-surveillance',
		'tower',
		'basics:icon-observation_tower',
		'watermill',
		'basics:icon-watermill',
		'windmill',
		'basics:icon-windmill',
		'',
	],
	historic: [
		'match',
		['get', 'historic'],
		'artwork',
		'basics:icon-artwork',
		'castle',
		'basics:icon-castle',
		'monument',
		'basics:icon-monument',
		'wayside_shrine',
		'basics:icon-shrine',
		'basics:icon-historic',
	],
	emergency: [
		'match',
		['get', 'emergency'],
		'defibrillator',
		'basics:icon-defibrillator',
		'fire_hydrant',
		'basics:icon-hydrant',
		'phone',
		'basics:icon-emergency_phone',
		'',
	],
};

const POI_KEYS = ['amenity', 'leisure', 'tourism', 'shop', 'man_made', 'historic', 'emergency', 'highway', 'office'];

export function* pois(ctx: LayerContext): Generator<b.TaggedLayer> {
	// POI icons are SDF sprites: their translucency lives in the `labelPoi` token's alpha, which we
	// route to the symbol opacity (icon-opacity) — icons/text are drawn in the opaque colour, so the
	// text-color stays fully opaque (matching OSM Bright) while the icons fade.
	const iconColor = ctx.c.labelPoi.opaque();
	const iconOpacity = ctx.c.labelPoi.alpha;
	for (const key of POI_KEYS) {
		yield b.symbol('poi-' + key, {
			sourceLayer: 'pois',
			filter: ['to-boolean', ['get', key]],
			minzoom: 14, // Shortbread `pois` appear at z14 (matches OSM Bright poi layers)
			iconSize: { 16: 0.5, 19: 0.5, 20: 1 },
			opacity: iconOpacity,
			symbolPlacement: 'point',
			iconOptional: true,
			font: ctx.fonts.normal,
			color: iconColor,
			textHaloColor: ctx.bg, // OSM Bright POI halos are opaque (≈ white in light mode)
			textHaloWidth: 1,
			textHaloBlur: 0.5,
			image: IMAGES[key],
			group: 'pois',
		});
	}
}
