import type { LayerContext } from '../context.js';
import * as b from '../build.js';

// Point-of-interest icons. All share a common base style (the old `poi-*` rule) and add an
// icon `match` expression keyed on the relevant OSM tag (`highway` and `office` each carry a
// single Shortbread value, so their match has one entry).

// Icon match expressions (verbatim from the v5/old rules table), keyed by POI category.
const IMAGES: Record<string, unknown> = {
	amenity: [
		'match',
		['get', 'amenity'],
		'arts_centre',
		'base:icon-art_gallery',
		'clinic',
		'base:icon-doctor',
		'courthouse',
		'base:icon-justice',
		'food_court',
		'base:icon-restaurant',
		'public_building',
		'base:icon-town_hall',
		'university',
		'base:icon-college',
		'atm',
		'base:icon-atm',
		'bank',
		'base:icon-bank',
		'bar',
		'base:icon-bar',
		'bench',
		'base:icon-bench',
		'bicycle_rental',
		'base:icon-bicycle_share',
		'biergarten',
		'base:icon-beer_mug',
		'cafe',
		'base:icon-cafe',
		'car_rental',
		'base:icon-car_rental',
		'car_sharing',
		'base:icon-car_rental',
		'car_wash',
		'base:icon-car_wash',
		'cinema',
		'base:icon-cinema',
		'college',
		'base:icon-college',
		'community_centre',
		'base:icon-community',
		'dentist',
		'base:icon-dentist',
		'doctors',
		'base:icon-doctor',
		'drinking_water',
		'base:icon-drinking_water',
		'embassy',
		'base:icon-embassy',
		'fast_food',
		'base:icon-fast_food',
		'fire_station',
		'base:icon-fire_station',
		'fountain',
		'base:icon-fountain',
		'fuel',
		'base:icon-fuel_pump',
		'grave_yard',
		'base:icon-cemetery',
		'hospital',
		'base:icon-hospital',
		'hunting_stand',
		'base:icon-hunting_stand',
		'library',
		'base:icon-library',
		'marketplace',
		'base:icon-marketplace',
		'nightclub',
		'base:icon-nightclub',
		'nursing_home',
		'base:icon-nursing_home',
		'pharmacy',
		'base:icon-pill',
		'place_of_worship',
		[
			'match',
			['get', 'religion'],
			'christian',
			'base:icon-latin_cross',
			'muslim',
			'base:icon-star_and_crescent',
			'jewish',
			'base:icon-star_of_david',
			'buddhist',
			'base:icon-dharma_wheel',
			'hindu',
			'base:icon-om',
			'sikh',
			'base:icon-khanda',
			'taoist',
			'base:icon-yin_yang',
			'base:icon-person_kneeling_and_praying', // fallback: religion missing or unrecognized
		],
		'police',
		'base:icon-police_officer',
		'post_box',
		'base:icon-postbox',
		'post_office',
		'base:icon-post',
		'prison',
		'base:icon-prison',
		'pub',
		'base:icon-pint_glass',
		'recycling',
		'base:icon-recycling',
		'restaurant',
		'base:icon-restaurant',
		'school',
		'base:icon-school',
		'shelter',
		'base:icon-shelter',
		'telephone',
		'base:icon-telephone',
		'theatre',
		'base:icon-theater',
		'toilets',
		'base:icon-restrooms',
		'townhall',
		'base:icon-town_hall',
		'vending_machine',
		'base:icon-vending_machine',
		'veterinary',
		'base:icon-veterinary',
		'waste_basket',
		'base:icon-waste_basket',
		'base:transport-information', // generic "point of interest" fallback
	],
	leisure: [
		'match',
		['get', 'leisure'],
		'dog_park',
		'base:icon-dog',
		'golf_course',
		'base:icon-golf',
		'ice_rink',
		'base:icon-ice_rink',
		'pitch',
		'base:icon-pitch',
		'playground',
		'base:icon-seesaw',
		'stadium',
		'base:icon-stadium',
		'swimming_pool',
		'base:icon-swimming',
		'water_park',
		'base:icon-water_park',
		'base:icon-sports',
	],
	tourism: [
		'match',
		['get', 'tourism'],
		'artwork',
		'base:icon-artwork',
		'alpine_hut',
		'base:icon-chalet',
		'bed_and_breakfast',
		'base:icon-lodging',
		'camp_site',
		'base:icon-campsite',
		'caravan_site',
		'base:icon-caravan',
		'guest_house',
		'base:icon-lodging',
		'hostel',
		'base:icon-lodging',
		'hotel',
		'base:icon-lodging',
		'motel',
		'base:icon-lodging',
		'theme_park',
		'base:icon-amusement_park',
		'chalet',
		'base:icon-chalet',
		'information',
		'base:transport-information',
		'picnic_site',
		'base:icon-picnic_site',
		'viewpoint',
		'base:icon-viewpoint',
		'zoo',
		'base:icon-zoo',
		'base:transport-information', // generic "point of interest" fallback
	],
	shop: [
		'match',
		['get', 'shop'],
		'alcohol',
		'base:icon-alcohol_shop',
		'bakery',
		'base:icon-bakery',
		'beauty',
		'base:icon-beauty',
		'beverages',
		'base:icon-beverages',
		'books',
		'base:icon-books',
		'butcher',
		'base:icon-butcher',
		'chemist',
		'base:icon-tube_and_toothbrush',
		'clothes',
		'base:icon-clothes',
		'doityourself',
		'base:icon-do_it_yourself',
		'dry_cleaning',
		'base:icon-dry_cleaning',
		'florist',
		'base:icon-florist',
		'furniture',
		'base:icon-furniture',
		'garden_centre',
		'base:icon-garden_center',
		'general',
		'base:icon-shop',
		'gift',
		'base:icon-gift',
		'greengrocer',
		'base:icon-greengrocer',
		'hairdresser',
		'base:icon-scissors_and_comb',
		'hardware',
		'base:icon-hardware',
		'jewelry',
		'base:icon-ring',
		'kiosk',
		'base:icon-newspaper',
		'laundry',
		'base:icon-laundry',
		'newsagent',
		'base:icon-newsagent',
		'optician',
		'base:icon-optician',
		'outdoor',
		'base:icon-outdoor',
		'shoes',
		'base:icon-shoes',
		'sports',
		'base:icon-sports',
		'stationery',
		'base:icon-stationery',
		'toys',
		'base:icon-rocking_horse',
		'travel_agency',
		'base:icon-travel_agent',
		'video',
		'base:icon-video',
		'base:icon-shop',
	],
	man_made: [
		'match',
		['get', 'man_made'],
		'lighthouse',
		'base:icon-lighthouse',
		'wastewater_plant',
		'base:icon-wastewater',
		'water_well',
		'base:icon-drinking_water',
		'water_works',
		'base:icon-waterworks',
		'surveillance',
		'base:icon-surveillance',
		'tower',
		'base:icon-observation_tower',
		'watermill',
		'base:icon-watermill',
		'windmill',
		'base:icon-windmill',
		'base:transport-information', // generic "point of interest" fallback
	],
	historic: [
		'match',
		['get', 'historic'],
		'castle',
		'base:icon-castle',
		'monument',
		'base:icon-monument',
		'wayside_shrine',
		'base:icon-shrine',
		'base:icon-historic',
	],
	emergency: [
		'match',
		['get', 'emergency'],
		'defibrillator',
		'base:icon-defibrillator',
		'fire_hydrant',
		'base:icon-hydrant',
		'phone',
		'base:icon-emergency_phone',
		'',
	],
	highway: ['match', ['get', 'highway'], 'emergency_access_point', 'base:icon-emergency_access', ''],
	office: ['match', ['get', 'office'], 'diplomatic', 'base:icon-embassy', ''],
};

const POI_KEYS = ['amenity', 'leisure', 'tourism', 'shop', 'man_made', 'historic', 'emergency', 'highway', 'office'];

export function* pois(ctx: LayerContext): Generator<b.TaggedLayer> {
	// POI icons are SDF sprites: their translucency lives in the `labelPoi` token's alpha, applied via
	// symbol `opacity` — which covers both the icon and the label, so they share the opaque `labelPoi`
	// colour and the same alpha. From z19 the POI's name is drawn as a label beneath the icon, in the
	// same colour as the icon.
	const iconColor = ctx.c.labelPoi.opaque();
	const iconOpacity = ctx.c.labelPoi.alpha;
	for (const key of POI_KEYS) {
		yield b.symbol('poi-' + key, {
			sourceLayer: 'pois',
			filter: ['to-boolean', ['get', key]],
			minzoom: 14, // Shortbread `pois` appear at z14 (matches OSM Bright poi layers)
			iconSize: { base: 2, stops: { 16: 0.4, 20: 1.2 } },
			iconOpacity: { 16: 0, 17: iconOpacity },
			textOpacity: { 19: 0, 19.5: iconOpacity },
			// Name label under the icon, appearing from z19+. `text-size` is 0 below z18 so the label
			// adds no collision box at mid zoom (only icons compete there), and an empty name renders
			// nothing. `textOptional` keeps the icon visible even when the label can't be placed.
			text: ctx.nameField,
			size: { 18: 0, 19: 11, 22: 13 },
			textAnchor: 'top',
			textOffset: [0, 1.2],
			textOptional: true,
			symbolPlacement: 'point',
			iconOptional: true,
			font: ctx.fonts.bold,
			color: iconColor,
			textHaloColor: ctx.bg, // OSM Bright POI halos are opaque (≈ white in light mode)
			textHaloWidth: 0.5,
			textHaloBlur: 0.5,
			image: IMAGES[key],
			group: 'pois',
		});
	}
}
