import type { FilterSpecification } from '@maplibre/maplibre-gl-style-spec';
import type { LayerContext } from '../context.js';
import type { Color } from '../../color/index.js';
import type { MaplibreLayerDefinition } from '../../types/index.js';
import * as b from '../build.js';

// Roads, paths, rail, aerialways and ferries.
//
// Render structure (tunnel / surface / bridge levels × outline / fill / bridge-deck × type) is
// generated by `buildStructures`; each layer's fully-resolved paint/layout is then computed
// inline by `roadStyle` from the parsed layer id — no rule table, no wildcard matching.

const lineCap = 'round';
const lineJoin = 'round';

// ── Layer structures (tunnel / surface / bridge levels + rail/aerialway/ferry) ──

function buildStructures(): MaplibreLayerDefinition[] {
	return (['tunnel', 'street', 'bridge'] as const).flatMap((c): MaplibreLayerDefinition[] => {
		let filter: FilterSpecification[];
		let prefix: string;
		let suffixes: string[];

		switch (c) {
			case 'tunnel':
				filter = [['==', ['get', 'tunnel'], true] as FilterSpecification];
				prefix = 'tunnel-';
				suffixes = [':outline', ''];
				break;
			case 'street':
				filter = [
					['!=', ['get', 'bridge'], true] as FilterSpecification,
					['!=', ['get', 'tunnel'], true] as FilterSpecification,
				];
				prefix = '';
				suffixes = [':outline', ''];
				break;
			case 'bridge':
				filter = [['==', ['get', 'bridge'], true] as FilterSpecification];
				prefix = 'bridge-';
				suffixes = [':bridge', ':outline', ''];
				break;
		}

		const results: MaplibreLayerDefinition[] = [];

		if (c === 'street') results.push({ id: 'bridge', type: 'fill', 'source-layer': 'bridges' });

		for (const suffix of suffixes) {
			if (suffix === ':outline')
				results.push({
					id: prefix + 'street-pedestrian-zone',
					type: 'fill',
					'source-layer': 'street_polygons',
					filter: ['all', ...filter, ['==', ['get', 'kind'], 'pedestrian']] as FilterSpecification,
				});

			for (const t of ['footway', 'steps', 'path', 'cycleway']) {
				results.push({
					id: prefix + 'way-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ...filter, ['==', ['get', 'kind'], t]] as FilterSpecification,
				});
			}

			for (const t of [
				'track',
				'pedestrian',
				'service',
				'living_street',
				'residential',
				'unclassified',
				'busway',
				'bus_guideway',
			]) {
				results.push({
					id: prefix + 'street-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ['==', ['get', 'kind'], t], ...filter] as FilterSpecification,
				});
			}

			if (suffix === '')
				for (const t of ['track', 'pedestrian', 'service', 'living_street', 'residential', 'unclassified']) {
					results.push({
						id: prefix + 'street-' + t.replace(/_/g, '') + '-bicycle',
						type: 'line',
						'source-layer': 'streets',
						filter: [
							'all',
							['==', ['get', 'kind'], t],
							['==', ['get', 'bicycle'], 'designated'],
							...filter,
						] as FilterSpecification,
					});
				}

			for (const t of ['tertiary', 'secondary', 'primary', 'trunk', 'motorway']) {
				results.push({
					id: prefix + 'street-' + t.replace(/_/g, '') + '-link' + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ...filter, ['==', ['get', 'kind'], t], ['==', ['get', 'link'], true]] as FilterSpecification,
				});
			}

			for (const t of ['tertiary', 'secondary', 'primary', 'trunk', 'motorway']) {
				results.push({
					id: prefix + 'street-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ...filter, ['==', ['get', 'kind'], t], ['!=', ['get', 'link'], true]] as FilterSpecification,
				});
			}
		}

		for (const suffix of [':outline', ''] as const) {
			for (const t of ['tram', 'narrow_gauge', 'subway', 'light_rail', 'rail'].reverse()) {
				results.push({
					id: prefix + 'transport-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ['==', ['get', 'kind'], t], ['!', ['has', 'service']], ...filter] as FilterSpecification,
				});
				results.push({
					id: prefix + 'transport-' + t.replace(/_/g, '') + '-service' + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ['==', ['get', 'kind'], t], ['has', 'service'], ...filter] as FilterSpecification,
				});
			}
			for (const t of ['monorail', 'funicular'].reverse()) {
				results.push({
					id: prefix + 'transport-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ['==', ['get', 'kind'], t], ...filter] as FilterSpecification,
				});
			}

			if (c === 'street') {
				for (const t of [
					'rope-tow',
					'platter',
					'j-bar',
					't-bar',
					'drag_lift',
					'chair_lift',
					'goods',
					'gondola',
					'cable_car',
				].reverse()) {
					results.push({
						id: 'aerialway-' + t.replace(/[_-]+/g, '') + suffix,
						type: 'line',
						'source-layer': 'aerialways',
						filter: ['all', ...filter, ['==', ['get', 'kind'], t]] as FilterSpecification,
					});
				}
				results.push({ id: 'transport-ferry' + suffix, type: 'line', 'source-layer': 'ferries' });
			}
		}

		return results;
	});
}

// ── Inline style resolution ────────────────────────────────────────────────────

type Prefix = '' | 'tunnel-' | 'bridge-';

// The old VersaTiles road widths: hand-tuned linear stops (no exponential base) that stay thin at
// low/mid zoom and ramp up steeply past z16, reaching their full chunky width at z19–20.
const MINOR_WIDTH = {
	outline: { 12: 2, 14: 3, 16: 6, 18: 26, 19: 64, 20: 128 },
	main: { 12: 1, 14: 2, 16: 5, 18: 24, 19: 60, 20: 120 },
};

// The arterial classes drawn in the yellow/orange palette. In the old VersaTiles style tertiary is
// NOT arterial — it's a white minor road — so it is deliberately absent here.
const YELLOW = new Set(['motorway', 'trunk', 'primary', 'secondary']);
const isServiceLike = (base: string): boolean => base === 'service' || base === 'busway' || base === 'busguideway';

// Shortbread `streets` schema minzoom per road kind — the zoom at which each kind first appears
// in the tiles (https://shortbread-tiles.org/schema/1.0/). Roads blend in from 0 width here.
const STREET_APPEAR: Record<string, number> = {
	motorway: 5,
	trunk: 6,
	primary: 8,
	secondary: 9,
	tertiary: 10,
	residential: 12,
	unclassified: 12,
	busway: 12,
	busguideway: 12,
	livingstreet: 13,
	pedestrian: 13,
	service: 13,
	track: 13,
};

function streetAppear(base: string, isLink: boolean): number {
	// The `link` flag is only populated from z11; OSM Bright renders motorway ramps from z12, the rest z13.
	if (isLink) return base === 'motorway' ? 12 : 13;
	return STREET_APPEAR[base] ?? 12;
}

// Line width by base street type — the old VersaTiles curves. These are identical across surface,
// tunnel and bridge (the old style never varied fill/casing width by prefix; only the bridge deck,
// handled in `bridgeDeckStyle`, differs), so `prefix` is not consulted here.
function streetWidth(base: string, isLink: boolean, isOutline: boolean): { size: b.SizeValue } {
	if (isLink) {
		// tertiary-link follows the minor curve; every other link shares a common (thinner) curve.
		if (base === 'tertiary') return { size: isOutline ? MINOR_WIDTH.outline : MINOR_WIDTH.main };
		return isOutline
			? { size: { 12: 2, 14: 3, 16: 7, 18: 14, 20: 40 } }
			: { size: { 12: 1, 14: 2, 16: 5, 18: 12, 20: 38 } };
	}
	switch (base) {
		case 'motorway':
			return isOutline
				? { size: { 5: 0, 6: 2, 10: 5, 14: 5, 16: 14, 18: 38, 19: 84, 20: 168 } }
				: { size: { 5: 0, 6: 1, 10: 4, 14: 4, 16: 12, 18: 36, 19: 80, 20: 160 } };
		case 'trunk':
			return isOutline
				? { size: { 6: 0, 7: 2, 10: 4, 14: 6, 16: 12, 18: 36, 19: 74, 20: 144 } }
				: { size: { 6: 0, 7: 1, 10: 3, 14: 5, 16: 10, 18: 34, 19: 70, 20: 140 } };
		case 'primary':
			return isOutline
				? { size: { 8: 0, 9: 1, 10: 4, 14: 6, 16: 12, 18: 36, 19: 74, 20: 144 } }
				: { size: { 8: 0, 9: 2, 10: 3, 14: 5, 16: 10, 18: 34, 19: 70, 20: 140 } };
		case 'secondary':
			return isOutline
				? { size: { 11: 2, 14: 5, 16: 8, 18: 30, 19: 68, 20: 138 } }
				: { size: { 11: 1, 14: 4, 16: 6, 18: 28, 19: 64, 20: 130 } };
		case 'service':
		case 'busway':
		case 'busguideway':
			return isOutline
				? { size: { 14: 1, 16: 3, 18: 12, 19: 32, 20: 48 } }
				: { size: { 14: 1, 16: 2, 18: 10, 19: 28, 20: 40 } };
		case 'track':
			return isOutline
				? { size: { 14: 2, 16: 4, 18: 18, 19: 48, 20: 96 } }
				: { size: { 14: 1, 16: 3, 18: 16, 19: 44, 20: 88 } };
		default: // tertiary / residential / unclassified / livingstreet / pedestrian — the minor curve
			return { size: isOutline ? MINOR_WIDTH.outline : MINOR_WIDTH.main };
	}
}

// Surface fill (main) + casing (:outline) colors per class — the old VersaTiles road palette.
function classColors(c: LayerContext['c'], fg: Color, base: string): { main: Color; casing: Color } {
	if (base === 'motorway') return { main: c.roadMotorway, casing: c.roadMotorwayBg };
	if (YELLOW.has(base)) return { main: c.roadTrunk, casing: c.roadTrunkBg };
	// Pedestrian streets are drawn in the lavender foot color; service/bus in a faint off-white with a
	// slightly lighter casing. Everything else (tertiary/residential/unclassified/livingstreet/track)
	// is a plain white minor road with the warm-grey street casing.
	if (base === 'pedestrian') return { main: c.transitFoot, casing: c.roadStreetBg };
	if (isServiceLike(base))
		return { main: c.roadStreet.blend(0.03, fg), casing: c.roadStreetBg.blend(0.3, c.roadStreet) };
	return { main: c.roadStreet, casing: c.roadStreetBg };
}

function streetLineStyle(ctx: LayerContext, prefix: Prefix, t: string, isOutline: boolean): b.StyleProps {
	const { c, fg } = ctx;
	const isLink = t.endsWith('-link');
	const base = isLink ? t.slice(0, -5) : t;
	const { main, casing } = classColors(c, fg, base);
	const isYellow = YELLOW.has(base);

	const r: b.StyleProps = { lineJoin, lineCap };

	if (isOutline) {
		r.color = casing;
		if (prefix === 'tunnel-') {
			// Tunnels: yellow casings lighten a touch, service/bus casings stay as-is, the rest grey to
			// a light neutral.
			r.color = isYellow
				? casing.blend(0.05, c.roadStreet)
				: isServiceLike(base)
					? casing
					: c.roadStreet.blend(0.13, fg);
			// OSM Bright dashes tunnel casings for every class EXCEPT trunk and primary.
			if (base !== 'trunk' && base !== 'primary') r.lineDasharray = [0.5, 0.25];
		} else if (prefix === 'bridge-' && !isYellow && !isServiceLike(base)) {
			// Bridges lighten the white-minor / pedestrian casing to a neutral grey.
			r.color = c.roadStreet.blend(0.15, fg);
		}
	} else {
		r.color = main;
		// Tunnels lighten the yellow fills toward white and grey everything else to a faint off-white.
		if (prefix === 'tunnel-') r.color = isYellow ? main.blend(0.1, c.roadStreet) : c.roadStreet.blend(0.03, fg);
		// Pedestrian streets are lavender only on the surface; on bridges they render white.
		else if (prefix === 'bridge-' && base === 'pedestrian') r.color = c.roadStreet;
	}

	Object.assign(r, streetWidth(base, isLink, isOutline));

	// Every road type fades in by opacity (0 → 1) over its Shortbread appearance zoom z → z+1, so it
	// materializes smoothly instead of popping. Applies to both the casing (:outline) and the fill.
	r.opacity = b.fadeIn(streetAppear(base, isLink));

	return r;
}

function zoneStyle(ctx: LayerContext, prefix: Prefix): b.StyleProps {
	const { c, fg } = ctx;
	// surface: minor-width opacity {12:0,13:1} overlaid by the zone's {14:0,15:1}
	if (prefix === '') return { color: c.transitFoot, opacity: { 14: 0, 15: 1 } };
	if (prefix === 'tunnel-') return { color: c.roadStreet.blend(0.03, fg), opacity: { 12: 0, 13: 1 } };
	return { color: c.roadStreet, opacity: { 12: 0, 13: 1 } };
}

function bicycleStyle(ctx: LayerContext, prefix: Prefix, base: string): b.StyleProps {
	const { c, fg } = ctx;
	const r: b.StyleProps = { lineJoin, lineCap };
	r.color = prefix === 'tunnel-' ? c.roadStreet.blend(0.03, fg) : c.roadStreet;
	// minor width for these bicycle overlays (track/service overlays get none)
	if (base === 'residential' || base === 'unclassified' || base === 'livingstreet' || base === 'pedestrian') {
		r.size = MINOR_WIDTH.main;
		r.opacity = { 12: 0, 13: 1 };
		r.color = c.transitCycle;
		r.lineCap = 'round';
	}
	return r;
}

// Path-class ways (footway/steps/path/cycleway), old VersaTiles style: a solid line with a matching
// casing, growing in from 0 width at z15. footway/steps/path use the lavender foot color; cycleway
// the light-blue cycle color. Tunnels dash the fill; bridges also get a deck (see bridgeDeckStyle).
function wayStyle(ctx: LayerContext, prefix: Prefix, t: string, isOutline: boolean): b.StyleProps | null {
	const { c, fg } = ctx;
	const fill = t === 'cycleway' ? c.transitCycle : c.transitFoot;

	if (isOutline) {
		// Casing: the fill darkened ~10% (matches the old style's outline tint), solid in every prefix.
		return {
			color: fill.blend(0.1, fg),
			lineJoin,
			lineCap,
			size: { 15: 0, 16: 5, 18: 7, 19: 12, 20: 22 },
		};
	}
	return {
		color: fill,
		lineJoin,
		lineCap,
		size: { 15: 0, 16: 4, 18: 6, 19: 10, 20: 20 },
		// Tunnels dash the path fill; surface and bridge paths are solid.
		...(prefix === 'tunnel-' ? { lineDasharray: [1, 0.2] } : {}),
	};
}

// Returns null for variants that should not be drawn at all (e.g. ferry casing,
// service-track rail/subway/tram) so the caller skips them instead of emitting a bare layer.
function transportStyle(ctx: LayerContext, _prefix: Prefix, t: string, isOutline: boolean): b.StyleProps | null {
	const { c, fg } = ctx;
	// railways interpolate with base 1.4 in OSM Bright
	const w14 = (stops: Record<number, number>): b.ExpStops => ({ base: 1.4, stops });

	if (t === 'ferry')
		return isOutline
			? null
			: {
					minzoom: 10,
					// closest derivation of OSM Bright's ferry teal (#6c9fb6) from the single water color;
					// blend toward `fg` (black in light mode / white in dark mode) rather than absolute darken
					color: c.water.saturate(0.8).blend(0.3, fg),
					size: 1.1,
					opacity: { 10: 0, 11: 1 },
					lineDasharray: [2, 2],
					lineJoin, // OSM Bright: ferry cap butt (default) / join round
				};

	const isService = t.endsWith('-service');
	const rt = isService ? t.slice(0, -'-service'.length) : t;

	let r: b.StyleProps | null;
	if (rt === 'rail' || rt === 'lightrail') {
		// OSM Bright railways: a thin solid base line (:outline) with a wider dashed "hatching"
		// line on top (the fill), producing the cross-tie look.
		if (isService)
			r = isOutline
				? { color: c.transitRail, size: w14({ 14: 0.4, 20: 1 }) }
				: { color: c.transitRail, lineDasharray: [0.2, 8], size: w14({ 14.5: 0, 15: 2, 20: 6 }) };
		else
			r = isOutline
				? { color: c.transitRail, size: w14({ 14: 0.4, 15: 0.75, 20: 2 }) }
				: { color: c.transitRail, lineDasharray: [0.2, 8], size: w14({ 14.5: 0, 15: 3, 20: 8 }) };
	} else if (rt === 'subway') {
		if (isService) return null;
		// transit/subway: same hatching technique, in a slightly translucent grey.
		r = isOutline
			? { color: c.transitSubway, size: w14({ 14: 0.4, 20: 1 }) }
			: { color: c.transitSubway, lineDasharray: [0.2, 8], size: w14({ 14.5: 0, 15: 2, 20: 6 }) };
	} else {
		// tram / narrowgauge / funicular / monorail
		if (isService) return null;
		r = isOutline
			? { minzoom: 15, color: c.transitRail, size: { 15: 0, 16: 5, 18: 7, 20: 20 }, lineDasharray: [0.1, 0.5] }
			: { minzoom: 13, size: { 13: 0, 16: 1, 17: 2, 18: 3, 20: 5 }, color: c.transitRail };
	}

	// Rail tracks fade in by opacity over z14→15 — the zoom at which OSM Bright starts drawing rail
	// (the width curves are ~0 below 14) — for both the base (:outline) and the hatching (fill).
	r.opacity = b.fadeIn(14);
	return r;
}

function bridgeDeckStyle(ctx: LayerContext, s: string): b.StyleProps {
	const { c, fg } = ctx;
	const base: b.StyleProps = {
		lineCap,
		lineJoin,
		color: c.land.blend(0.02, fg),
		fillAntialias: true,
		opacity: 0.5,
	};
	if (s.startsWith('way-')) return { ...base, size: { 15: 0, 16: 7, 18: 10, 19: 17, 20: 31 }, minzoom: 15 };

	const t = s.slice('street-'.length);
	const isLink = t.endsWith('-link');
	const bt = isLink ? t.slice(0, -5) : t;

	if (isLink) {
		if (bt === 'motorway') return { ...base, minzoom: 12, size: { 12: 3, 14: 4, 16: 10, 18: 20, 20: 56 } };
		if (bt === 'trunk' || bt === 'primary' || bt === 'secondary')
			return { ...base, minzoom: 13, size: { 12: 3, 14: 4, 16: 10, 18: 20, 20: 56 } };
		// tertiary-link → minor deck
		return { ...base, size: { 12: 3, 14: 4, 16: 8, 18: 36, 19: 90, 20: 179 }, opacity: { 12: 0, 13: 1 } };
	}
	switch (bt) {
		case 'motorway':
			return { ...base, size: { 5: 0, 6: 3, 10: 7, 14: 7, 16: 20, 18: 53, 19: 118, 20: 235 } };
		case 'trunk':
			return { ...base, size: { 7: 0, 8: 3, 10: 6, 14: 8, 16: 17, 18: 50, 19: 104, 20: 202 } };
		case 'primary':
			return { ...base, size: { 8: 0, 9: 1, 10: 6, 14: 8, 16: 17, 18: 50, 19: 104, 20: 202 } };
		case 'secondary':
			return { ...base, size: { 11: 3, 14: 7, 16: 11, 18: 42, 19: 95, 20: 193 }, opacity: { 11: 0, 12: 1 } };
		case 'tertiary':
		case 'unclassified':
		case 'residential':
		case 'livingstreet':
		case 'pedestrian':
			return { ...base, size: { 12: 3, 14: 4, 16: 8, 18: 36, 19: 90, 20: 179 }, opacity: { 12: 0, 13: 1 } };
		case 'service':
		case 'track':
			return { ...base, size: { 14: 3, 16: 6, 18: 25, 19: 67, 20: 134 }, opacity: { 14: 0, 15: 1 } };
		default: // busway, busguideway
			return base;
	}
}

// Compute the fully-resolved style for a road layer from its id.
// Returns the resolved style for a road layer, or null when the layer should not be
// drawn (no styling rule). Every non-null result carries a color, so the caller can
// safely treat it as a colored style for the mandatory-color fill/line builders.
function roadStyle(ctx: LayerContext, id: string): b.StyleProps | null {
	if (id === 'bridge') return { color: ctx.c.land.blend(0.02, ctx.fg), fillAntialias: true, opacity: 0.8 };

	let prefix: Prefix = '';
	let s = id;
	if (s.startsWith('tunnel-')) {
		prefix = 'tunnel-';
		s = s.slice(7);
	} else if (s.startsWith('bridge-')) {
		prefix = 'bridge-';
		s = s.slice(7);
	}

	let suffix: '' | ':outline' | ':bridge' = '';
	if (s.endsWith(':outline')) {
		suffix = ':outline';
		s = s.slice(0, -8);
	} else if (s.endsWith(':bridge')) {
		suffix = ':bridge';
		s = s.slice(0, -7);
	}

	if (suffix === ':bridge') return bridgeDeckStyle(ctx, s);
	if (s.startsWith('aerialway-')) {
		// Aerialways (cable cars / lifts), OSM Bright style: a thin solid base line (:outline)
		// with a wider dashed line on top (the fill) giving the cable-tick pattern.
		// OSM Bright caps cable-cars round and joins them miter.
		if (suffix === ':outline')
			return { color: ctx.c.transitRail, minzoom: 13, size: { base: 1, stops: { 11: 1, 19: 2.5 } }, lineCap };
		return {
			color: ctx.c.transitRail,
			minzoom: 13,
			size: { base: 1, stops: { 11: 3, 19: 5.5 } },
			lineDasharray: [2, 3],
			lineCap,
		};
	}
	if (s.startsWith('transport-'))
		return transportStyle(ctx, prefix, s.slice('transport-'.length), suffix === ':outline');
	if (s.startsWith('way-')) return wayStyle(ctx, prefix, s.slice('way-'.length), suffix === ':outline');
	if (s.startsWith('street-')) {
		const t = s.slice('street-'.length);
		if (t === 'pedestrian-zone') return zoneStyle(ctx, prefix);
		if (t.endsWith('-bicycle')) return bicycleStyle(ctx, prefix, t.slice(0, -'-bicycle'.length));
		return streetLineStyle(ctx, prefix, t, suffix === ':outline');
	}
	return null;
}

// ── Group tagging (mirrors the old groups.ts road membership) ──────────────────

function roadGroup(id: string): string | undefined {
	if (id.startsWith('aerialway-')) return 'transit.aerialways';
	const s = id.replace(/^(tunnel-|bridge-)/, '');
	if (s.startsWith('transport-ferry')) return 'transit.ferries';
	if (s.startsWith('transport-')) return 'transit.rail';
	if (id === 'bridge') return 'roads.motorways';
	if (s.startsWith('way-steps')) return 'roads.steps';
	if (s.startsWith('way-footway')) return 'roads.footway';
	if (s.startsWith('way-')) return 'roads.paths';
	if (s.startsWith('street-')) {
		let t = s.slice('street-'.length).replace(/(:outline|:bridge)$/, '');
		t = t.replace(/-(link|bicycle|zone)$/, '');
		switch (t) {
			case 'motorway':
			case 'trunk':
				return 'roads.motorways';
			case 'primary':
			case 'secondary':
			case 'tertiary':
				return 'roads.highways';
			case 'residential':
			case 'livingstreet':
			case 'unclassified':
				return 'roads.streets.residential';
			case 'service':
				return 'roads.streets.service';
			case 'pedestrian':
				return 'roads.streets.pedestrian';
			case 'track':
				return 'roads.streets.track';
			case 'busway':
			case 'busguideway':
				return 'roads.streets.bus';
		}
	}
	return undefined;
}

export function* roads(ctx: LayerContext): Generator<b.TaggedLayer> {
	for (const def of buildStructures()) {
		// every road structure is a fill or line layer (never background)
		const d = def as { id: string; type: string; 'source-layer': string; filter?: FilterSpecification };
		const style = roadStyle(ctx, d.id);
		if (!style) continue; // no styling rule → don't emit a bare (black) layer
		// A bridge is a mid-road section that must join flush to the surface road at both ends, so its
		// line ends use butt caps (like the old VersaTiles style). Round caps would round off the bridge
		// end into a bulge that overlaps the road it continues, making one street look like two
		// overlapping outlined pieces. Surface and tunnel roads keep round caps.
		if (d.type === 'line' && d.id.startsWith('bridge-')) (style as b.StyleProps).lineCap = 'butt';
		const make = d.type === 'fill' ? b.fill : b.line;
		// roadStyle guarantees a color for every non-null result (see its contract).
		yield make(d.id, {
			sourceLayer: d['source-layer'],
			filter: d.filter,
			...(style as b.ColoredStyleProps),
			group: roadGroup(d.id),
		});
	}
}
