import type { FilterSpecification } from '@maplibre/maplibre-gl-style-spec';
import type { LayerContext } from '../context.js';
import type { Color } from '../../color/index.js';
import type { MaplibreLayerDefinition } from '../../types/index.js';
import * as b from '../build.js';

// Roads, paths, rail, aerialways and ferries.
//
// Render structure (tunnel / surface / bridge levels × outline / fill / bridge-deck × type) is
// generated by `buildStructures`; each layer's fully-resolved paint/layout is then computed
// inline by `roadStyle` from the parsed layer id — no rule table, no wildcard matching.

const lineCap = 'round';
const lineJoin = 'round';

// ── Layer structures (tunnel / surface / bridge levels + rail/aerialway/ferry) ──

function buildStructures(): MaplibreLayerDefinition[] {
	return (['tunnel', 'street', 'bridge'] as const).flatMap((c): MaplibreLayerDefinition[] => {
		let filter: FilterSpecification[];
		let prefix: string;
		let suffixes: string[];

		switch (c) {
			case 'tunnel':
				filter = [['==', ['get', 'tunnel'], true] as FilterSpecification];
				prefix = 'tunnel-';
				suffixes = [':outline', ''];
				break;
			case 'street':
				filter = [
					['!=', ['get', 'bridge'], true] as FilterSpecification,
					['!=', ['get', 'tunnel'], true] as FilterSpecification,
				];
				prefix = '';
				suffixes = [':outline', ''];
				break;
			case 'bridge':
				filter = [['==', ['get', 'bridge'], true] as FilterSpecification];
				prefix = 'bridge-';
				suffixes = [':bridge', ':outline', ''];
				break;
		}

		const results: MaplibreLayerDefinition[] = [];

		if (c === 'street') results.push({ id: 'bridge', type: 'fill', 'source-layer': 'bridges' });

		for (const suffix of suffixes) {
			if (suffix === ':outline')
				results.push({
					id: prefix + 'street-pedestrian-zone',
					type: 'fill',
					'source-layer': 'street_polygons',
					filter: ['all', ...filter, ['==', ['get', 'kind'], 'pedestrian']] as FilterSpecification,
				});

			for (const t of ['footway', 'steps', 'path', 'cycleway']) {
				results.push({
					id: prefix + 'way-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ...filter, ['==', ['get', 'kind'], t]] as FilterSpecification,
				});
			}

			for (const t of [
				'track',
				'pedestrian',
				'service',
				'living_street',
				'residential',
				'unclassified',
				'busway',
				'bus_guideway',
			]) {
				results.push({
					id: prefix + 'street-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ['==', ['get', 'kind'], t], ...filter] as FilterSpecification,
				});
			}

			if (suffix === '')
				for (const t of ['track', 'pedestrian', 'service', 'living_street', 'residential', 'unclassified']) {
					results.push({
						id: prefix + 'street-' + t.replace(/_/g, '') + '-bicycle',
						type: 'line',
						'source-layer': 'streets',
						filter: [
							'all',
							['==', ['get', 'kind'], t],
							['==', ['get', 'bicycle'], 'designated'],
							...filter,
						] as FilterSpecification,
					});
				}

			for (const t of ['tertiary', 'secondary', 'primary', 'trunk', 'motorway']) {
				results.push({
					id: prefix + 'street-' + t.replace(/_/g, '') + '-link' + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ...filter, ['==', ['get', 'kind'], t], ['==', ['get', 'link'], true]] as FilterSpecification,
				});
			}

			for (const t of ['tertiary', 'secondary', 'primary', 'trunk', 'motorway']) {
				results.push({
					id: prefix + 'street-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ...filter, ['==', ['get', 'kind'], t], ['!=', ['get', 'link'], true]] as FilterSpecification,
				});
			}
		}

		for (const suffix of [':outline', ''] as const) {
			for (const t of ['tram', 'narrow_gauge', 'subway', 'light_rail', 'rail'].reverse()) {
				results.push({
					id: prefix + 'transport-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ['==', ['get', 'kind'], t], ['!', ['has', 'service']], ...filter] as FilterSpecification,
				});
				results.push({
					id: prefix + 'transport-' + t.replace(/_/g, '') + '-service' + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ['==', ['get', 'kind'], t], ['has', 'service'], ...filter] as FilterSpecification,
				});
			}
			for (const t of ['monorail', 'funicular'].reverse()) {
				results.push({
					id: prefix + 'transport-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ['==', ['get', 'kind'], t], ...filter] as FilterSpecification,
				});
			}

			if (c === 'street') {
				for (const t of [
					'rope-tow',
					'platter',
					'j-bar',
					't-bar',
					'drag_lift',
					'chair_lift',
					'goods',
					'gondola',
					'cable_car',
				].reverse()) {
					results.push({
						id: 'aerialway-' + t.replace(/[_-]+/g, '') + suffix,
						type: 'line',
						'source-layer': 'aerialways',
						filter: ['all', ...filter, ['==', ['get', 'kind'], t]] as FilterSpecification,
					});
				}
				results.push({ id: 'transport-ferry' + suffix, type: 'line', 'source-layer': 'ferries' });
			}
		}

		return results;
	});
}

// ── Inline style resolution ────────────────────────────────────────────────────

type Prefix = '' | 'tunnel-' | 'bridge-';

// OpenMapTiles / OSM Bright interpolate widths exponentially with base 1.2.
const BASE = 1.2;
const exp = (stops: Record<number, number>): b.ExpStops => ({ base: BASE, stops });

const MINOR_WIDTH = {
	outline: { 12: 2, 14: 3, 16: 6, 18: 26, 19: 64, 20: 128 },
	main: { 12: 1, 14: 2, 16: 5, 18: 24, 19: 60, 20: 120 },
};

const ARTERIAL = new Set(['motorway', 'trunk', 'primary', 'secondary', 'tertiary']);

// Shortbread `streets` schema minzoom per road kind — the zoom at which each kind first appears
// in the tiles (https://shortbread-tiles.org/schema/1.0/). Roads blend in from 0 width here.
const STREET_APPEAR: Record<string, number> = {
	motorway: 5,
	trunk: 6,
	primary: 8,
	secondary: 9,
	tertiary: 10,
	residential: 12,
	unclassified: 12,
	busway: 12,
	busguideway: 12,
	livingstreet: 13,
	pedestrian: 13,
	service: 13,
	track: 13,
};

function streetAppear(base: string, isLink: boolean): number {
	// The `link` flag is only populated from z11; OSM Bright renders motorway ramps from z12, the rest z13.
	if (isLink) return base === 'motorway' ? 12 : 13;
	return STREET_APPEAR[base] ?? 12;
}

// Line width by base street type and prefix — the OSM-Bright-matched curves. Roads draw at their
// natural width as soon as their data appears and fade in by opacity (see `streetLineStyle`), so no
// width blend is applied here. OSM Bright widens casings on bridges and thins service/track in
// tunnels, so widths resolve per (base × prefix × outline/fill).
function streetWidth(
	base: string,
	isLink: boolean,
	isOutline: boolean,
	prefix: Prefix
): { minzoom?: number; size: b.ExpStops } {
	if (isLink) {
		const minzoom = base === 'motorway' ? 12 : 13;
		return isOutline
			? { minzoom, size: exp({ 12: 1, 13: 3, 14: 4, 20: 15 }) }
			: { minzoom, size: exp({ 12.5: 0, 13: 1.5, 14: 2.5, 20: 11.5 }) };
	}
	const bridge = prefix === 'bridge-';
	switch (base) {
		case 'motorway':
			return isOutline
				? { size: exp(bridge ? { 5: 0.4, 6: 0.6, 7: 1.5, 20: 26 } : { 4: 0, 5: 0.4, 6: 0.6, 7: 1.5, 20: 22 }) }
				: { size: exp({ 6.5: 0, 7: 0.5, 20: 18 }) };
		case 'trunk':
			return isOutline
				? { size: exp(bridge ? { 5: 0.4, 6: 0.6, 7: 1.5, 20: 26 } : { 5: 0, 6: 0.6, 7: 1.5, 20: 22 }) }
				: { size: exp({ 6.5: 0, 7: 0.5, 20: 18 }) };
		case 'primary':
			// OSM Bright groups primary BRIDGES/TUNNELS with trunk (a wider/earlier curve) vs the surface.
			if (prefix !== '')
				return isOutline
					? { size: exp({ 5: 0.4, 6: 0.6, 7: 1.5, 20: bridge ? 26 : 22 }) }
					: { size: exp({ 6.5: 0, 7: 0.5, 20: 18 }) };
			return isOutline
				? { minzoom: 5, size: exp({ 7: 0, 8: 0.6, 9: 1.5, 20: 22 }) }
				: { size: exp({ 8.5: 0, 9: 0.5, 20: 18 }) };
		case 'secondary':
		case 'tertiary':
			return isOutline
				? { size: exp(bridge ? { 5: 0.4, 7: 0.6, 8: 1.5, 20: 21 } : { 8: 1.5, 20: 17 }) }
				: { size: exp({ 6.5: 0, 8: 0.5, 20: 13 }) };
		default: // minor / service / track / residential / unclassified / living_street / pedestrian / busway
			// OSM Bright draws service/track thinner inside tunnels.
			if (prefix === 'tunnel-' && (base === 'service' || base === 'track'))
				return isOutline ? { size: exp({ 15: 1, 16: 4, 20: 11 }) } : { size: exp({ 15.5: 0, 16: 2, 20: 7.5 }) };
			return isOutline
				? { size: exp(bridge ? { 12: 0.5, 13: 1, 14: 6, 20: 24 } : { 12: 0.5, 13: 1, 14: 4, 20: 15 }) }
				: { size: exp({ 13: 0, 14: 2.5, 20: 11.5 }) };
	}
}

// Fill (main) + casing (:outline) colors per class, matching OSM Bright.
function classColors(c: LayerContext['c'], base: string): { main: Color; casing: Color } {
	if (base === 'motorway') return { main: c.roadMotorway, casing: c.roadMotorwayBg };
	if (ARTERIAL.has(base)) return { main: c.roadTrunk, casing: c.roadTrunkBg };
	return { main: c.roadStreet, casing: c.roadStreetBg };
}

function streetLineStyle(ctx: LayerContext, prefix: Prefix, t: string, isOutline: boolean): b.StyleProps {
	const { c, bg } = ctx;
	const isLink = t.endsWith('-link');
	const base = isLink ? t.slice(0, -5) : t;
	const { main, casing } = classColors(c, base);
	const isArterial = ARTERIAL.has(base);

	const r: b.StyleProps = { lineJoin, lineCap };

	if (isOutline) {
		r.color = casing;
		// OSM Bright dashes tunnel casings for every class EXCEPT trunk and primary.
		if (prefix === 'tunnel-' && base !== 'trunk' && base !== 'primary') r.lineDasharray = [0.5, 0.25];
	} else {
		r.color = main;
		// OSM Bright tunnels render a lighter fill (the arterial classes only; minor stays white).
		if (prefix === 'tunnel-') {
			if (base === 'motorway') r.color = main.blend(0.2, bg);
			else if (isArterial) r.color = main.blend(0.33, bg);
		}
	}

	Object.assign(r, streetWidth(base, isLink, isOutline, prefix));

	// Every road type fades in by opacity (0 → 1) over its Shortbread appearance zoom z → z+1, so it
	// materializes smoothly instead of popping. Applies to both the casing (:outline) and the fill.
	r.opacity = b.fadeIn(streetAppear(base, isLink));

	return r;
}

function zoneStyle(ctx: LayerContext, prefix: Prefix): b.StyleProps {
	const { c, fg } = ctx;
	// surface: minor-width opacity {12:0,13:1} overlaid by the zone's {14:0,15:1}
	if (prefix === '') return { color: c.transitFoot, opacity: { 14: 0, 15: 0.5 } };
	if (prefix === 'tunnel-') return { color: c.roadStreet.blend(0.03, fg), opacity: { 12: 0, 13: 1 } };
	return { color: c.roadStreet, opacity: { 12: 0, 13: 1 } };
}

function bicycleStyle(ctx: LayerContext, prefix: Prefix, base: string): b.StyleProps {
	const { c, fg } = ctx;
	const r: b.StyleProps = { lineJoin, lineCap };
	r.color = prefix === 'tunnel-' ? c.roadStreet.blend(0.03, fg) : c.roadStreet;
	// minor width for these bicycle overlays (track/service overlays get none)
	if (base === 'residential' || base === 'unclassified' || base === 'livingstreet' || base === 'pedestrian') {
		r.size = MINOR_WIDTH.main;
		r.opacity = { 12: 0, 13: 1 };
		r.color = c.transitCycle;
		r.lineCap = 'round';
	}
	return r;
}

// OSM Bright renders all path-class ways (footway/path/cycleway/steps) as a single dashed tan
// line with no casing. `_t` (way type) is kept for signature symmetry with the other builders.
function wayStyle(ctx: LayerContext, prefix: Prefix, t: string, isOutline: boolean): b.StyleProps | null {
	const { c } = ctx;
	// Paths (footway/steps/path/cycleway) appear in Shortbread at z13. They're thin dashed lines, so a
	// width grow-in makes the dashes scale and reads as a snap; instead they keep their full width and
	// fade in via opacity over z13→14 — drawn the moment their data appears, materializing smoothly.
	if (isOutline) {
		// OSM Bright gives bridge paths a casing; surface/tunnel paths have none.
		if (prefix !== 'bridge-') return null;
		return {
			color: c.roadStreetBg,
			lineJoin,
			lineCap,
			size: { base: 1.2, stops: { 15: 1.2, 20: 18 } },
			opacity: b.fadeIn(13),
		};
	}
	return {
		color: c.land.darken(0.18).blend(0.22, c.roadMotorwayBg), // ≈ #cba
		lineJoin,
		lineCap,
		size: { base: 1.2, stops: { 15: 1.2, 20: 4 } },
		lineDasharray: [1.5, 0.75],
		opacity: b.fadeIn(13),
	};
}

// Returns null for variants that should not be drawn at all (e.g. ferry casing,
// service-track rail/subway/tram) so the caller skips them instead of emitting a bare layer.
function transportStyle(ctx: LayerContext, _prefix: Prefix, t: string, isOutline: boolean): b.StyleProps | null {
	const { c } = ctx;
	// railways interpolate with base 1.4 in OSM Bright
	const w14 = (stops: Record<number, number>): b.ExpStops => ({ base: 1.4, stops });

	if (t === 'ferry')
		return isOutline
			? null
			: {
				minzoom: 10,
				// closest derivation of OSM Bright's ferry teal (#6c9fb6) from the single water color
				color: c.water.saturate(0.8).darken(0.3),
				size: 1.1,
				opacity: { 10: 0, 11: 1 },
				lineDasharray: [2, 2],
				lineJoin, // OSM Bright: ferry cap butt (default) / join round
			};

	const isService = t.endsWith('-service');
	const rt = isService ? t.slice(0, -'-service'.length) : t;

	let r: b.StyleProps | null;
	if (rt === 'rail' || rt === 'lightrail') {
		// OSM Bright railways: a thin solid base line (:outline) with a wider dashed "hatching"
		// line on top (the fill), producing the cross-tie look.
		if (isService)
			r = isOutline
				? { color: c.transitRail, size: w14({ 14: 0.4, 20: 1 }) }
				: { color: c.transitRail, lineDasharray: [0.2, 8], size: w14({ 14.5: 0, 15: 2, 20: 6 }) };
		else
			r = isOutline
				? { color: c.transitRail, size: w14({ 14: 0.4, 15: 0.75, 20: 2 }) }
				: { color: c.transitRail, lineDasharray: [0.2, 8], size: w14({ 14.5: 0, 15: 3, 20: 8 }) };
	} else if (rt === 'subway') {
		if (isService) return null;
		// transit/subway: same hatching technique, in a slightly translucent grey.
		r = isOutline
			? { color: c.transitSubway.fade(0.23), size: w14({ 14: 0.4, 20: 1 }) }
			: { color: c.transitSubway.fade(0.32), lineDasharray: [0.2, 8], size: w14({ 14.5: 0, 15: 2, 20: 6 }) };
	} else {
		// tram / narrowgauge / funicular / monorail
		if (isService) return null;
		r = isOutline
			? { minzoom: 15, color: c.transitRail, size: { 15: 0, 16: 5, 18: 7, 20: 20 }, lineDasharray: [0.1, 0.5] }
			: { minzoom: 13, size: { 13: 0, 16: 1, 17: 2, 18: 3, 20: 5 }, color: c.transitRail };
	}

	// Rail tracks fade in by opacity over z14→15 — the zoom at which OSM Bright starts drawing rail
	// (the width curves are ~0 below 14) — for both the base (:outline) and the hatching (fill).
	r.opacity = b.fadeIn(14);
	return r;
}

function bridgeDeckStyle(ctx: LayerContext, s: string): b.StyleProps {
	const { c, fg } = ctx;
	const base: b.StyleProps = {
		lineCap,
		lineJoin,
		color: c.land.blend(0.02, fg),
		fillAntialias: true,
		opacity: 0.5,
	};
	if (s.startsWith('way-')) return { ...base, size: { 15: 0, 16: 7, 18: 10, 19: 17, 20: 31 }, minzoom: 15 };

	const t = s.slice('street-'.length);
	const isLink = t.endsWith('-link');
	const bt = isLink ? t.slice(0, -5) : t;

	if (isLink) {
		if (bt === 'motorway') return { ...base, minzoom: 12, size: { 12: 3, 14: 4, 16: 10, 18: 20, 20: 56 } };
		if (bt === 'trunk' || bt === 'primary' || bt === 'secondary')
			return { ...base, minzoom: 13, size: { 12: 3, 14: 4, 16: 10, 18: 20, 20: 56 } };
		// tertiary-link → minor deck
		return { ...base, size: { 12: 3, 14: 4, 16: 8, 18: 36, 19: 90, 20: 179 }, opacity: { 12: 0, 13: 1 } };
	}
	switch (bt) {
		case 'motorway':
			return { ...base, size: { 5: 0, 6: 3, 10: 7, 14: 7, 16: 20, 18: 53, 19: 118, 20: 235 } };
		case 'trunk':
			return { ...base, size: { 7: 0, 8: 3, 10: 6, 14: 8, 16: 17, 18: 50, 19: 104, 20: 202 } };
		case 'primary':
			return { ...base, size: { 8: 0, 9: 1, 10: 6, 14: 8, 16: 17, 18: 50, 19: 104, 20: 202 } };
		case 'secondary':
			return { ...base, size: { 11: 3, 14: 7, 16: 11, 18: 42, 19: 95, 20: 193 }, opacity: { 11: 0, 12: 1 } };
		case 'tertiary':
		case 'unclassified':
		case 'residential':
		case 'livingstreet':
		case 'pedestrian':
			return { ...base, size: { 12: 3, 14: 4, 16: 8, 18: 36, 19: 90, 20: 179 }, opacity: { 12: 0, 13: 1 } };
		case 'service':
		case 'track':
			return { ...base, size: { 14: 3, 16: 6, 18: 25, 19: 67, 20: 134 }, opacity: { 14: 0, 15: 1 } };
		default: // busway, busguideway
			return base;
	}
}

// Compute the fully-resolved style for a road layer from its id.
// Returns the resolved style for a road layer, or null when the layer should not be
// drawn (no styling rule). Every non-null result carries a color, so the caller can
// safely treat it as a colored style for the mandatory-color fill/line builders.
function roadStyle(ctx: LayerContext, id: string): b.StyleProps | null {
	if (id === 'bridge') return { color: ctx.c.land.blend(0.02, ctx.fg), fillAntialias: true, opacity: 0.8 };

	let prefix: Prefix = '';
	let s = id;
	if (s.startsWith('tunnel-')) {
		prefix = 'tunnel-';
		s = s.slice(7);
	} else if (s.startsWith('bridge-')) {
		prefix = 'bridge-';
		s = s.slice(7);
	}

	let suffix: '' | ':outline' | ':bridge' = '';
	if (s.endsWith(':outline')) {
		suffix = ':outline';
		s = s.slice(0, -8);
	} else if (s.endsWith(':bridge')) {
		suffix = ':bridge';
		s = s.slice(0, -7);
	}

	if (suffix === ':bridge') return bridgeDeckStyle(ctx, s);
	if (s.startsWith('aerialway-')) {
		// Aerialways (cable cars / lifts), OSM Bright style: a thin solid base line (:outline)
		// with a wider dashed line on top (the fill) giving the cable-tick pattern.
		// OSM Bright caps cable-cars round and joins them miter.
		if (suffix === ':outline')
			return { color: ctx.c.transitRail, minzoom: 13, size: { base: 1, stops: { 11: 1, 19: 2.5 } }, lineCap };
		return {
			color: ctx.c.transitRail,
			minzoom: 13,
			size: { base: 1, stops: { 11: 3, 19: 5.5 } },
			lineDasharray: [2, 3],
			lineCap,
		};
	}
	if (s.startsWith('transport-'))
		return transportStyle(ctx, prefix, s.slice('transport-'.length), suffix === ':outline');
	if (s.startsWith('way-')) return wayStyle(ctx, prefix, s.slice('way-'.length), suffix === ':outline');
	if (s.startsWith('street-')) {
		const t = s.slice('street-'.length);
		if (t === 'pedestrian-zone') return zoneStyle(ctx, prefix);
		if (t.endsWith('-bicycle')) return bicycleStyle(ctx, prefix, t.slice(0, -'-bicycle'.length));
		return streetLineStyle(ctx, prefix, t, suffix === ':outline');
	}
	return null;
}

// ── Group tagging (mirrors the old groups.ts road membership) ──────────────────

function roadGroup(id: string): string | undefined {
	if (id.startsWith('aerialway-')) return 'transit.aerialways';
	const s = id.replace(/^(tunnel-|bridge-)/, '');
	if (s.startsWith('transport-ferry')) return 'transit.ferries';
	if (s.startsWith('transport-')) return 'transit.rail';
	if (id === 'bridge') return 'roads.motorways';
	if (s.startsWith('way-')) return 'roads.paths';
	if (s.startsWith('street-')) {
		let t = s.slice('street-'.length).replace(/(:outline|:bridge)$/, '');
		t = t.replace(/-(link|bicycle|zone)$/, '');
		switch (t) {
			case 'motorway':
			case 'trunk':
				return 'roads.motorways';
			case 'primary':
			case 'secondary':
			case 'tertiary':
				return 'roads.highways';
			case 'residential':
			case 'livingstreet':
			case 'unclassified':
				return 'roads.streets.residential';
			case 'service':
				return 'roads.streets.service';
			case 'pedestrian':
				return 'roads.streets.pedestrian';
			case 'track':
				return 'roads.streets.track';
			case 'busway':
			case 'busguideway':
				return 'roads.streets.bus';
		}
	}
	return undefined;
}

export function* roads(ctx: LayerContext): Generator<b.TaggedLayer> {
	for (const def of buildStructures()) {
		// every road structure is a fill or line layer (never background)
		const d = def as { id: string; type: string; 'source-layer': string; filter?: FilterSpecification };
		const style = roadStyle(ctx, d.id);
		if (!style) continue; // no styling rule → don't emit a bare (black) layer
		const make = d.type === 'fill' ? b.fill : b.line;
		// roadStyle guarantees a color for every non-null result (see its contract).
		yield make(d.id, {
			sourceLayer: d['source-layer'],
			filter: d.filter,
			...(style as b.ColoredStyleProps),
			group: roadGroup(d.id),
		});
	}
}
