import type { FilterSpecification } from '@maplibre/maplibre-gl-style-spec';
import type { LayerContext } from '../context.js';
import type { MaplibreLayerDefinition } from '../../types/index.js';
import * as b from '../build.js';

// Roads, paths, rail, aerialways and ferries.
//
// Render structure (tunnel / surface / bridge levels × outline / fill / bridge-deck × type) is
// generated by `buildStructures`; each layer's fully-resolved paint/layout is then computed
// inline by `roadStyle` from the parsed layer id — no rule table, no wildcard matching.

// ── Layer structures (tunnel / surface / bridge levels + rail/aerialway/ferry) ──

function buildStructures(): MaplibreLayerDefinition[] {
	return (['tunnel', 'street', 'bridge'] as const).flatMap((c): MaplibreLayerDefinition[] => {
		let filter: FilterSpecification[];
		let prefix: string;
		let suffixes: string[];

		switch (c) {
			case 'tunnel':
				filter = [['==', ['get', 'tunnel'], true] as FilterSpecification];
				prefix = 'tunnel-';
				suffixes = [':outline', ''];
				break;
			case 'street':
				filter = [
					['!=', ['get', 'bridge'], true] as FilterSpecification,
					['!=', ['get', 'tunnel'], true] as FilterSpecification,
				];
				prefix = '';
				suffixes = [':outline', ''];
				break;
			case 'bridge':
				filter = [['==', ['get', 'bridge'], true] as FilterSpecification];
				prefix = 'bridge-';
				suffixes = [':bridge', ':outline', ''];
				break;
		}

		const results: MaplibreLayerDefinition[] = [];

		if (c === 'street') results.push({ id: 'bridge', type: 'fill', 'source-layer': 'bridges' });

		for (const suffix of suffixes) {
			if (suffix === ':outline')
				results.push({
					id: prefix + 'street-pedestrian-zone',
					type: 'fill',
					'source-layer': 'street_polygons',
					filter: ['all', ...filter, ['==', ['get', 'kind'], 'pedestrian']] as FilterSpecification,
				});

			for (const t of ['footway', 'steps', 'path', 'cycleway']) {
				results.push({
					id: prefix + 'way-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ...filter, ['==', ['get', 'kind'], t]] as FilterSpecification,
				});
			}

			for (const t of [
				'track',
				'pedestrian',
				'service',
				'living_street',
				'residential',
				'unclassified',
				'busway',
				'bus_guideway',
			]) {
				results.push({
					id: prefix + 'street-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ['==', ['get', 'kind'], t], ...filter] as FilterSpecification,
				});
			}

			if (suffix === '')
				for (const t of ['track', 'pedestrian', 'service', 'living_street', 'residential', 'unclassified']) {
					results.push({
						id: prefix + 'street-' + t.replace(/_/g, '') + '-bicycle',
						type: 'line',
						'source-layer': 'streets',
						filter: [
							'all',
							['==', ['get', 'kind'], t],
							['==', ['get', 'bicycle'], 'designated'],
							...filter,
						] as FilterSpecification,
					});
				}

			for (const t of ['tertiary', 'secondary', 'primary', 'trunk', 'motorway']) {
				results.push({
					id: prefix + 'street-' + t.replace(/_/g, '') + '-link' + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ...filter, ['==', ['get', 'kind'], t], ['==', ['get', 'link'], true]] as FilterSpecification,
				});
			}

			for (const t of ['tertiary', 'secondary', 'primary', 'trunk', 'motorway']) {
				results.push({
					id: prefix + 'street-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ...filter, ['==', ['get', 'kind'], t], ['!=', ['get', 'link'], true]] as FilterSpecification,
				});
			}
		}

		for (const suffix of [':outline', ''] as const) {
			for (const t of ['tram', 'narrow_gauge', 'subway', 'light_rail', 'rail'].reverse()) {
				results.push({
					id: prefix + 'transport-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ['==', ['get', 'kind'], t], ['!', ['has', 'service']], ...filter] as FilterSpecification,
				});
				results.push({
					id: prefix + 'transport-' + t.replace(/_/g, '') + '-service' + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ['==', ['get', 'kind'], t], ['has', 'service'], ...filter] as FilterSpecification,
				});
			}
			for (const t of ['monorail', 'funicular'].reverse()) {
				results.push({
					id: prefix + 'transport-' + t.replace(/_/g, '') + suffix,
					type: 'line',
					'source-layer': 'streets',
					filter: ['all', ['==', ['get', 'kind'], t], ...filter] as FilterSpecification,
				});
			}

			if (c === 'street') {
				for (const t of [
					'rope-tow',
					'platter',
					'j-bar',
					't-bar',
					'drag_lift',
					'chair_lift',
					'goods',
					'gondola',
					'cable_car',
				].reverse()) {
					results.push({
						id: 'aerialway-' + t.replace(/[_-]+/g, '') + suffix,
						type: 'line',
						'source-layer': 'aerialways',
						filter: ['all', ...filter, ['==', ['get', 'kind'], t]] as FilterSpecification,
					});
				}
				results.push({ id: 'transport-ferry' + suffix, type: 'line', 'source-layer': 'ferries' });
			}
		}

		return results;
	});
}

// ── Inline style resolution ────────────────────────────────────────────────────

type Prefix = '' | 'tunnel-' | 'bridge-';

const MINOR_WIDTH = {
	outline: { 12: 2, 14: 3, 16: 6, 18: 26, 19: 64, 20: 128 },
	main: { 12: 1, 14: 2, 16: 5, 18: 24, 19: 60, 20: 120 },
};

// width (and link min-zoom) by base street type
function streetWidth(base: string, isLink: boolean, isOutline: boolean): b.StyleProps {
	if (isLink) {
		if (base === 'motorway')
			return isOutline
				? { minzoom: 12, size: { 12: 2, 14: 3, 16: 7, 18: 14, 20: 40 } }
				: { minzoom: 12, size: { 12: 1, 14: 2, 16: 5, 18: 12, 20: 38 } };
		if (base === 'trunk' || base === 'primary' || base === 'secondary')
			return isOutline
				? { minzoom: 13, size: { 12: 2, 14: 3, 16: 7, 18: 14, 20: 40 } }
				: { minzoom: 13, size: { 12: 1, 14: 2, 16: 5, 18: 12, 20: 38 } };
		// tertiary-link → minor
		return { size: isOutline ? MINOR_WIDTH.outline : MINOR_WIDTH.main, opacity: { 12: 0, 13: 1 } };
	}
	switch (base) {
		case 'motorway':
			return isOutline
				? { size: { 5: 0, 6: 2, 10: 5, 14: 5, 16: 14, 18: 38, 19: 84, 20: 168 } }
				: { size: { 5: 0, 6: 1, 10: 4, 14: 4, 16: 12, 18: 36, 19: 80, 20: 160 }, opacity: { 5: 0, 6: 1 } };
		case 'trunk':
			return isOutline
				? { size: { 6: 0, 7: 2, 10: 4, 14: 6, 16: 12, 18: 36, 19: 74, 20: 144 } }
				: { size: { 6: 0, 7: 1, 10: 3, 14: 5, 16: 10, 18: 34, 19: 70, 20: 140 }, opacity: { 6: 0, 7: 1 } };
		case 'primary':
			return isOutline
				? { size: { 8: 0, 9: 1, 10: 4, 14: 6, 16: 12, 18: 36, 19: 74, 20: 144 } }
				: { size: { 8: 0, 9: 2, 10: 3, 14: 5, 16: 10, 18: 34, 19: 70, 20: 140 }, opacity: { 8: 0, 9: 1 } };
		case 'secondary':
			return isOutline
				? { size: { 11: 2, 14: 5, 16: 8, 18: 30, 19: 68, 20: 138 }, opacity: { 11: 0, 12: 1 } }
				: { size: { 11: 1, 14: 4, 16: 6, 18: 28, 19: 64, 20: 130 }, opacity: { 11: 0, 12: 1 } };
		case 'track':
			return isOutline
				? { size: { 14: 2, 16: 4, 18: 18, 19: 48, 20: 96 }, opacity: { 14: 0, 15: 1 } }
				: { size: { 14: 1, 16: 3, 18: 16, 19: 44, 20: 88 }, opacity: { 14: 0, 15: 1 } };
		case 'service':
		case 'busway':
		case 'busguideway':
			return isOutline
				? { size: { 14: 1, 16: 3, 18: 12, 19: 32, 20: 48 }, opacity: { 15: 0, 16: 1 } }
				: { size: { 14: 1, 16: 2, 18: 10, 19: 28, 20: 40 }, opacity: { 15: 0, 16: 1 } };
		default: // tertiary, unclassified, residential, livingstreet, pedestrian
			return { size: isOutline ? MINOR_WIDTH.outline : MINOR_WIDTH.main, opacity: { 12: 0, 13: 1 } };
	}
}

function streetLineStyle(ctx: LayerContext, prefix: Prefix, t: string, isOutline: boolean): b.StyleProps {
	const { c, bg, fg } = ctx;
	const isLink = t.endsWith('-link');
	const base = isLink ? t.slice(0, -5) : t;
	const r: b.StyleProps = {};

	// base street color + join
	r.color = isOutline ? c.roadStreetBg : c.roadStreet;
	r.lineJoin = 'round';
	// tunnel / bridge color blends
	if (prefix === 'tunnel-') r.color = isOutline ? c.roadStreet.blend(0.13, fg) : c.roadStreet.blend(0.03, fg);
	else if (prefix === 'bridge-' && isOutline) r.color = c.roadStreet.blend(0.15, fg);
	// line cap
	r.lineCap = prefix === 'bridge-' ? 'butt' : 'round';

	// arterial color overrides (motorway / trunk-class), incl. -link
	if (base === 'motorway') {
		if (isOutline) {
			r.color = prefix === 'tunnel-' ? c.roadMotorwayBg.blend(0.05, bg) : c.roadMotorwayBg;
			if (prefix === 'tunnel-') r.lineDasharray = [1, 0.3];
		} else {
			r.color = prefix === 'tunnel-' ? c.roadMotorway.blend(0.1, bg) : c.roadMotorway;
			if (prefix === 'tunnel-') r.lineCap = 'butt';
		}
	} else if (base === 'trunk' || base === 'primary' || base === 'secondary') {
		if (isOutline) {
			r.color = prefix === 'tunnel-' ? c.roadTrunkBg.blend(0.05, bg) : c.roadTrunkBg;
			if (prefix === 'tunnel-') r.lineDasharray = [1, 0.3];
		} else {
			r.color = prefix === 'tunnel-' ? c.roadTrunk.blend(0.1, bg) : c.roadTrunk;
			if (prefix === 'tunnel-') r.lineCap = 'butt';
		}
	}

	// service / bus color
	if (base === 'service' || base === 'busway' || base === 'busguideway')
		r.color = isOutline ? c.roadStreetBg.blend(0.3, bg) : c.roadStreet.blend(0.03, fg);

	// pedestrian surface main color
	const isPedSurfaceMain = base === 'pedestrian' && !isLink && prefix === '' && !isOutline;
	if (isPedSurfaceMain) r.color = c.transitFoot;

	// width + opacity
	Object.assign(r, streetWidth(base, isLink, isOutline));
	// surface pedestrian: the minor-width opacity {12:0,13:1} is overlaid by {13:0,14:1}
	if (isPedSurfaceMain) r.opacity = { ...(r.opacity as Record<number, number>), 13: 0, 14: 1 };

	return r;
}

function zoneStyle(ctx: LayerContext, prefix: Prefix): b.StyleProps {
	const { c, bg, fg } = ctx;
	// surface: minor-width opacity {12:0,13:1} overlaid by the zone's {14:0,15:1}
	if (prefix === '')
		return { color: c.transitFoot.blend(0.02, bg).fade(0.75), opacity: { 12: 0, 13: 1, 14: 0, 15: 1 } };
	if (prefix === 'tunnel-') return { color: c.roadStreet.blend(0.03, fg), opacity: { 12: 0, 13: 1 } };
	return { color: c.roadStreet, opacity: { 12: 0, 13: 1 } };
}

function bicycleStyle(ctx: LayerContext, prefix: Prefix, base: string): b.StyleProps {
	const { c, fg } = ctx;
	const r: b.StyleProps = { lineJoin: 'round', lineCap: prefix === 'bridge-' ? 'butt' : 'round' };
	r.color = prefix === 'tunnel-' ? c.roadStreet.blend(0.03, fg) : c.roadStreet;
	// minor width for these bicycle overlays (track/service overlays get none)
	if (base === 'residential' || base === 'unclassified' || base === 'livingstreet' || base === 'pedestrian') {
		r.size = MINOR_WIDTH.main;
		r.opacity = { 12: 0, 13: 1 };
		r.color = c.transitCycle;
		r.lineCap = 'round';
	}
	return r;
}

function wayStyle(ctx: LayerContext, prefix: Prefix, t: string, isOutline: boolean): b.StyleProps {
	const { c, bg, fg } = ctx;
	const r: b.StyleProps = {
		minzoom: 15,
		lineCap: prefix === 'bridge-' ? 'butt' : 'round',
		size: isOutline ? { 15: 0, 16: 5, 18: 7, 19: 12, 20: 22 } : { 15: 0, 16: 4, 18: 6, 19: 10, 20: 20 },
	};
	if (t === 'cycleway') {
		if (prefix === 'tunnel-') {
			r.color = isOutline
				? c.transitCycle.blend(0.1, fg).saturate(-0.5)
				: c.transitCycle.blend(0.02, fg).saturate(-0.5);
			if (!isOutline) r.lineDasharray = [1, 0.2];
		} else {
			r.color = isOutline ? c.transitCycle.blend(0.1, fg) : c.transitCycle;
		}
	} else {
		if (prefix === 'tunnel-') {
			r.color = isOutline ? c.transitFoot.blend(0.1, fg).saturate(-0.5) : c.transitFoot.blend(0.02, fg).saturate(-0.5);
			if (!isOutline) r.lineDasharray = [1, 0.2];
		} else {
			r.color = isOutline ? c.transitFoot.blend(0.1, fg) : c.transitFoot.blend(0.02, bg);
		}
	}
	return r;
}

// Returns null for variants that should not be drawn at all (e.g. ferry casing,
// service-track rail/subway/tram) so the caller skips them instead of emitting a bare layer.
function transportStyle(ctx: LayerContext, prefix: Prefix, t: string, isOutline: boolean): b.StyleProps | null {
	const { c, bg, fg } = ctx;
	if (t === 'ferry')
		return isOutline
			? null
			: {
					minzoom: 10,
					color: c.water.blend(0.1, fg),
					size: { 10: 1, 13: 2, 14: 3, 16: 4, 17: 6 },
					opacity: { 10: 0, 11: 1 },
					lineDasharray: [1, 1],
				};

	const isService = t.endsWith('-service');
	const rt = isService ? t.slice(0, -'-service'.length) : t;

	if (rt === 'rail' || rt === 'lightrail') {
		const r: b.StyleProps = {};
		if (isService) {
			if (isOutline) Object.assign(r, { color: c.transitRail, minzoom: 14, size: { 14: 0, 15: 1, 16: 1, 20: 14 } });
			else
				Object.assign(r, {
					color: c.transitRail.blend(0.25, bg),
					minzoom: 15,
					size: { 15: 0, 16: 1, 20: 10 },
					lineDasharray: [2, 2],
				});
			return r; // service variants carry no opacity rule
		}
		if (isOutline) Object.assign(r, { color: c.transitRail, minzoom: 8, size: { 8: 1, 13: 1, 15: 1, 20: 14 } });
		else
			Object.assign(r, {
				color: c.transitRail.blend(0.25, bg),
				minzoom: 14,
				size: { 14: 0, 15: 1, 20: 10 },
				lineDasharray: [2, 2],
			});
		if (rt === 'rail')
			r.opacity =
				prefix === 'tunnel-'
					? isOutline
						? { 8: 0, 9: 0.3 }
						: { 14: 0, 15: 0.3 }
					: isOutline
						? { 8: 0, 9: 1 }
						: { 14: 0, 15: 1 };
		else
			r.opacity =
				prefix === 'tunnel-'
					? isOutline
						? { 11: 0, 12: 0.5 }
						: { 14: 0, 15: 1 }
					: isOutline
						? { 11: 0, 12: 1 }
						: { 14: 0, 15: 1 };
		return r;
	}

	if (rt === 'subway') {
		if (isService) return null;
		const r: b.StyleProps = {};
		if (isOutline)
			Object.assign(r, { color: c.transitSubway, size: { 11: 0, 12: 1, 15: 3, 16: 3, 18: 6, 19: 8, 20: 10 } });
		else
			Object.assign(r, {
				color: c.transitSubway.blend(0.25, bg),
				size: { 11: 0, 12: 1, 15: 2, 16: 2, 18: 5, 19: 6, 20: 8 },
				lineDasharray: [2, 2],
			});
		r.opacity =
			prefix === 'tunnel-'
				? isOutline
					? { 11: 0, 12: 0.5 }
					: { 14: 0, 15: 1 }
				: isOutline
					? { 11: 0, 12: 1 }
					: { 14: 0, 15: 1 };
		return r;
	}

	// tram / narrowgauge / funicular / monorail
	if (isService) return null;
	return isOutline
		? { minzoom: 15, color: c.transitRail, size: { 15: 0, 16: 5, 18: 7, 20: 20 }, lineDasharray: [0.1, 0.5] }
		: { minzoom: 13, size: { 13: 0, 16: 1, 17: 2, 18: 3, 20: 5 }, color: c.transitRail };
}

function bridgeDeckStyle(ctx: LayerContext, s: string): b.StyleProps {
	const { c, fg } = ctx;
	const base: b.StyleProps = {
		lineCap: 'butt',
		lineJoin: 'round',
		color: c.land.blend(0.02, fg),
		fillAntialias: true,
		opacity: 0.5,
	};
	if (s.startsWith('way-')) return { ...base, size: { 15: 0, 16: 7, 18: 10, 19: 17, 20: 31 }, minzoom: 15 };

	const t = s.slice('street-'.length);
	const isLink = t.endsWith('-link');
	const bt = isLink ? t.slice(0, -5) : t;

	if (isLink) {
		if (bt === 'motorway') return { ...base, minzoom: 12, size: { 12: 3, 14: 4, 16: 10, 18: 20, 20: 56 } };
		if (bt === 'trunk' || bt === 'primary' || bt === 'secondary')
			return { ...base, minzoom: 13, size: { 12: 3, 14: 4, 16: 10, 18: 20, 20: 56 } };
		// tertiary-link → minor deck
		return { ...base, size: { 12: 3, 14: 4, 16: 8, 18: 36, 19: 90, 20: 179 }, opacity: { 12: 0, 13: 1 } };
	}
	switch (bt) {
		case 'motorway':
			return { ...base, size: { 5: 0, 6: 3, 10: 7, 14: 7, 16: 20, 18: 53, 19: 118, 20: 235 } };
		case 'trunk':
			return { ...base, size: { 7: 0, 8: 3, 10: 6, 14: 8, 16: 17, 18: 50, 19: 104, 20: 202 } };
		case 'primary':
			return { ...base, size: { 8: 0, 9: 1, 10: 6, 14: 8, 16: 17, 18: 50, 19: 104, 20: 202 } };
		case 'secondary':
			return { ...base, size: { 11: 3, 14: 7, 16: 11, 18: 42, 19: 95, 20: 193 }, opacity: { 11: 0, 12: 1 } };
		case 'tertiary':
		case 'unclassified':
		case 'residential':
		case 'livingstreet':
		case 'pedestrian':
			return { ...base, size: { 12: 3, 14: 4, 16: 8, 18: 36, 19: 90, 20: 179 }, opacity: { 12: 0, 13: 1 } };
		case 'service':
		case 'track':
			return { ...base, size: { 14: 3, 16: 6, 18: 25, 19: 67, 20: 134 }, opacity: { 14: 0, 15: 1 } };
		default: // busway, busguideway
			return base;
	}
}

// Compute the fully-resolved style for a road layer from its id.
// Returns the resolved style for a road layer, or null when the layer should not be
// drawn (no styling rule). Every non-null result carries a color, so the caller can
// safely treat it as a colored style for the mandatory-color fill/line builders.
function roadStyle(ctx: LayerContext, id: string): b.StyleProps | null {
	if (id === 'bridge') return { color: ctx.c.land.blend(0.02, ctx.fg), fillAntialias: true, opacity: 0.8 };

	let prefix: Prefix = '';
	let s = id;
	if (s.startsWith('tunnel-')) {
		prefix = 'tunnel-';
		s = s.slice(7);
	} else if (s.startsWith('bridge-')) {
		prefix = 'bridge-';
		s = s.slice(7);
	}

	let suffix: '' | ':outline' | ':bridge' = '';
	if (s.endsWith(':outline')) {
		suffix = ':outline';
		s = s.slice(0, -8);
	} else if (s.endsWith(':bridge')) {
		suffix = ':bridge';
		s = s.slice(0, -7);
	}

	if (suffix === ':bridge') return bridgeDeckStyle(ctx, s);
	if (s.startsWith('aerialway-')) {
		// Aerialways (cable cars / lifts): a single thin dashed line, no casing.
		if (suffix === ':outline') return null;
		return {
			color: ctx.c.transitRail.blend(0.2, ctx.bg),
			size: { 13: 0, 14: 1, 20: 2 },
			opacity: { 13: 0, 14: 0.6 },
			lineDasharray: [2, 2],
			lineJoin: 'round',
		};
	}
	if (s.startsWith('transport-'))
		return transportStyle(ctx, prefix, s.slice('transport-'.length), suffix === ':outline');
	if (s.startsWith('way-')) return wayStyle(ctx, prefix, s.slice('way-'.length), suffix === ':outline');
	if (s.startsWith('street-')) {
		const t = s.slice('street-'.length);
		if (t === 'pedestrian-zone') return zoneStyle(ctx, prefix);
		if (t.endsWith('-bicycle')) return bicycleStyle(ctx, prefix, t.slice(0, -'-bicycle'.length));
		return streetLineStyle(ctx, prefix, t, suffix === ':outline');
	}
	return null;
}

// ── Group tagging (mirrors the old groups.ts road membership) ──────────────────

function roadGroup(id: string): string | undefined {
	if (id.startsWith('aerialway-')) return 'transit.aerialways';
	const s = id.replace(/^(tunnel-|bridge-)/, '');
	if (s.startsWith('transport-ferry')) return 'transit.ferries';
	if (s.startsWith('transport-')) return 'transit.rail';
	if (id === 'bridge') return 'roads.motorways';
	if (s.startsWith('way-')) return 'roads.paths';
	if (s.startsWith('street-')) {
		let t = s.slice('street-'.length).replace(/(:outline|:bridge)$/, '');
		t = t.replace(/-(link|bicycle|zone)$/, '');
		switch (t) {
			case 'motorway':
			case 'trunk':
				return 'roads.motorways';
			case 'primary':
			case 'secondary':
			case 'tertiary':
				return 'roads.highways';
			case 'residential':
			case 'livingstreet':
			case 'unclassified':
				return 'roads.streets.residential';
			case 'service':
				return 'roads.streets.service';
			case 'pedestrian':
				return 'roads.streets.pedestrian';
			case 'track':
				return 'roads.streets.track';
			case 'busway':
			case 'busguideway':
				return 'roads.streets.bus';
		}
	}
	return undefined;
}

export function* roads(ctx: LayerContext): Generator<b.TaggedLayer> {
	for (const def of buildStructures()) {
		// every road structure is a fill or line layer (never background)
		const d = def as { id: string; type: string; 'source-layer': string; filter?: FilterSpecification };
		const style = roadStyle(ctx, d.id);
		if (!style) continue; // no styling rule → don't emit a bare (black) layer
		const make = d.type === 'fill' ? b.fill : b.line;
		// roadStyle guarantees a color for every non-null result (see its contract).
		yield make(d.id, {
			sourceLayer: d['source-layer'],
			filter: d.filter,
			...(style as b.ColoredStyleProps),
			group: roadGroup(d.id),
		});
	}
}
