// Icons for the `base` sheet — everything the style itself draws.
//
// `base` is INTERNAL. These names serve the style and may be renamed, added or removed with any
// release, so they carry no picker metadata; see icons-extras.ts for the public sheet.
//
// The key is the sprite name (`base:<group>-<key>`), the value is the file it is drawn from,
// relative to `icons/` and without the `.svg`. The two are deliberately independent — see
// SPRITES.md.
import type { IconSets } from '../lib/icons.js';

const icons: IconSets = {
	icon: {
		size: 22,
		icons: {
			airfield: 'maki/airfield',
			airport: 'maki/airport',
			alcohol_shop: 'maki/alcohol-shop',
			amusement_park: 'maki/amusement-park',
			art_gallery: 'maki/art-gallery',
			artwork: 'versatiles/artwork',
			atm: 'versatiles/atm',
			bakery: 'maki/bakery',
			bank: 'maki/bank',
			bar: 'maki/bar',
			beauty: 'versatiles/beauty',
			beer_mug: 'unknown/beer_mug',
			bench: 'versatiles/bench',
			beverages: 'versatiles/beverages',
			bicycle_share: 'maki/bicycle-share',
			books: 'versatiles/books',
			bus: 'temaki/bus',
			butcher: 'versatiles/butcher',
			cafe: 'maki/cafe',
			campsite: 'maki/campsite',
			car_rental: 'maki/car-rental',
			car_wash: 'versatiles/car_wash',
			caravan: 'unknown/caravan',
			castle: 'maki/castle',
			cemetery: 'maki/cemetery',
			chalet: 'versatiles/chalet',
			cinema: 'maki/cinema',
			clothes: 'versatiles/clothes',
			college: 'maki/college',
			community: 'versatiles/community',
			defibrillator: 'maki/defibrillator',
			dentist: 'maki/dentist',
			dharma_wheel: 'maki/religious-buddhist',
			do_it_yourself: 'versatiles/do_it_yourself',
			doctor: 'maki/doctor',
			dog: 'unknown/dog',
			drinking_water: 'maki/drinking-water',
			dry_cleaning: 'versatiles/dry_cleaning',
			embassy: 'maki/embassy',
			emergency_access: 'versatiles/emergency_access',
			emergency_phone: 'maki/emergency-phone',
			fast_food: 'maki/fast-food',
			fire_station: 'maki/fire-station',
			florist: 'maki/florist',
			fountain: 'unknown/fountain',
			fuel_pump: 'unknown/fuel_pump',
			furniture: 'maki/furniture',
			garden_center: 'maki/garden-centre',
			gift: 'maki/gift',
			golf: 'maki/golf',
			greengrocer: 'versatiles/greengrocer',
			hardware: 'maki/hardware',
			historic: 'maki/historic',
			hospital: 'maki/hospital',
			hunting_stand: 'versatiles/hunting_stand',
			hydrant: 'temaki/fire_hydrant',
			ice_rink: 'versatiles/ice_rink',
			justice: 'versatiles/justice',
			khanda: 'temaki/sikhism',
			latin_cross: 'unknown/latin_cross',
			laundry: 'maki/laundry',
			library: 'maki/library',
			lighthouse: 'maki/lighthouse',
			lodging: 'maki/lodging',
			marketplace: 'versatiles/marketplace',
			monument: 'maki/monument',
			newsagent: 'versatiles/newsagent',
			newspaper: 'unknown/newspaper',
			nightclub: 'versatiles/nightclub',
			nursing_home: 'versatiles/nursing_home',
			observation_tower: 'maki/observation-tower',
			om: 'temaki/hinduism',
			optician: 'maki/optician',
			outdoor: 'versatiles/outdoor',
			person_kneeling_and_praying: 'unknown/person_kneeling_and_praying',
			picnic_site: 'maki/picnic-site',
			pill: 'unknown/pill',
			pint_glass: 'unknown/pint_glass',
			pitch: 'maki/pitch',
			police_officer: 'temaki/police_officer',
			post: 'maki/post',
			postbox: 'versatiles/postbox',
			prison: 'maki/prison',
			rail: 'maki/rail',
			recycling: 'unknown/recycling',
			restaurant: 'maki/restaurant',
			restrooms: 'unknown/restrooms',
			ring: 'unknown/ring',
			rocking_horse: 'unknown/rocking_horse',
			school: 'maki/school',
			scissors_and_comb: 'temaki/beauty_salon',
			seesaw: 'temaki/seesaw',
			shelter: 'unknown/shelter',
			shoes: 'versatiles/shoes',
			shop: 'maki/shop',
			shrine: 'versatiles/shrine',
			sports: 'versatiles/sports',
			stadium: 'maki/stadium',
			star_and_crescent: 'maki/religious-muslim',
			star_of_david: 'unknown/star_of_david',
			stationery: 'versatiles/stationery',
			surveillance: 'versatiles/surveillance',
			swimming: 'maki/swimming',
			telephone: 'maki/telephone',
			theater: 'maki/theatre',
			town_hall: 'maki/town-hall',
			travel_agent: 'versatiles/travel_agent',
			tube_and_toothbrush: 'unknown/tube_and_toothbrush',
			vending_machine: 'unknown/vending_machine',
			veterinary: 'maki/veterinary',
			video: 'versatiles/video',
			viewpoint: 'maki/viewpoint',
			waste_basket: 'maki/waste-basket',
			wastewater: 'versatiles/wastewater',
			water_park: 'versatiles/water_park',
			watermill: 'maki/watermill',
			waterworks: 'versatiles/waterworks',
			windmill: 'maki/windmill',
			yin_yang: 'temaki/taoism',
			zoo: 'maki/zoo',
		},
	},
	marking: {
		size: 15,
		icons: {
			oneway: 'versatiles/oneway',
		},
	},
	// Tileable polygon fills for `fill-pattern`. Not SDF: MapLibre cannot recolour a fill
	// pattern, so these render as drawn. Every tile wraps seamlessly — see SPRITES.md.
	pattern: {
		useSDF: false,
		size: 16,
		icons: {
			hatched: 'versatiles/hatched',
			hatched_thin: 'versatiles/hatched_thin',
			striped: 'versatiles/striped',
		},
	},
	transport: {
		size: 22,
		icons: {
			information: 'versatiles/information',
			tram: 'temaki/tram',
		},
	},
};

export default icons;
