import type { FilterSpecification } from '@maplibre/maplibre-gl-style-spec';
import type { LayerContext } from '../context.js';
import type { Color } from '../../color/index.js';
import type { MaplibreLayerDefinition } from '../../types/index.js';
import * as b from '../../dsl/index.js';

// Roads, paths, rail, aerialways and ferries for OpenMapTiles — the largest module in the port.
//
// Structure (tunnel / surface / bridge levels × outline / fill / bridge-deck × type) is generated by
// `buildStructures`; each layer's paint/layout is then computed from its id by `roadStyle`, exactly as in
// the Shortbread module. **The style half below is carried over from `src/shortbread/layers/roads.ts`
// essentially verbatim** — see the note at the end of this header.
//
// ── What the tiles say ────────────────────────────────────────────────────────
//
// Everything structural here is from `npm run schema-values -- omt transportation`. Seven findings, in
// descending order of how much they changed the port:
//
//  1. **`minor` collapses three Shortbread kinds into one.** `residential`, `unclassified` and
//     `living_street` are all `class: minor`. Shortbread emits three layers and then merges two of them;
//     here there is one layer and nothing to merge. This is the port's largest single loss of fidelity,
//     and it is in the data, not in the style: no filter can separate a living street from a
//     residential one.
//  2. **`class: path` is the whole pedestrian family**, distinguished by `subclass`: footway, steps,
//     cycleway, pedestrian, path, corridor, platform. Shortbread gives each its own `kind`, so the
//     distinction survives — one level deeper.
//  3. **Mixed geometry.** `class: path` carries 598 polygons and 1291 lines; `bridge` is polygon-only;
//     `pier` is both. A line layer paints polygon boundaries, so every line structure filters
//     `LineString` and every area filters `Polygon`. Shortbread needed none of this: it separates
//     `streets` from `street_polygons`.
//  4. **The bridge deck area is `class: bridge`**, a polygon class of the same layer — not the separate
//     `bridges` source-layer Shortbread reads, and not gone as the gate first assumed.
//  5. **`oneway` is `1` / `-1`, not two booleans.** Shortbread carries `oneway` and `oneway_reverse`;
//     `-1` was observed, so the reverse case is expressible after all.
//  6. **`link` is `ramp: 1`**, and `tunnel`/`bridge` are the one `brunnel` enum.
//  7. **Aerialways need no per-kind layers.** Shortbread emits nine (cable_car, gondola, goods,
//     chair_lift, drag_lift, t-bar, j-bar, platter, rope-tow) and then merges all nine into one, because
//     they draw identically. `class: aerialway` is a single filter that does the same job, so the
//     `MERGES` entry that collapsed eighteen ids has no counterpart here.
//
// ── On the duplication ────────────────────────────────────────────────────────
//
// `roadStyle` and everything under it key on the **layer id**, never on a source-layer or a field, which
// is the 24/72 structure/style split SCHEMA-SUPPORT-PLAN.md §3 measured on this module. Porting it
// therefore needed four edits to ~320 lines of style code: `minor` added to `STREET_APPEAR`,
// `bridgeDeckStyle`, `bicycleStyle` and `roadGroup`, in place of Shortbread's three minor kinds.
//
// That is the sharpest evidence yet for the §7 step 8 decision, and it is recorded here rather than
// acted on: option A's accepted cost (risk 18) is that a cartographic fix now has to be made twice, and
// in this module "twice" means in two near-identical 320-line bodies. Extracting them is a decision for
// after the port, with both implementations in hand — which is exactly the evidence step 8 asked for.

const lineCap = 'round';
const lineJoin = 'round';

// ── Layer structures (tunnel / surface / bridge levels + rail/aerialway/ferry) ──

/** One source-layer carries both geometries, so every structure must say which one it wants (finding 3). */
const LINES: FilterSpecification = ['==', ['geometry-type'], 'LineString'];
const AREAS: FilterSpecification = ['==', ['geometry-type'], 'Polygon'];

/** `class` + `subclass` pairs for the path family, keyed by the layer id Shortbread uses (finding 2). */
const PATH_SUBCLASS: Record<string, string> = {
	footway: 'footway',
	steps: 'steps',
	path: 'path',
	cycleway: 'cycleway',
};

/** Rail-ish types: the id suffix, and the `class`/`subclass` pair that selects it (findings from zermatt). */
const RAIL_TYPES: { id: string; class: string; subclass: string; hasService: boolean }[] = [
	{ id: 'rail', class: 'rail', subclass: 'rail', hasService: true },
	{ id: 'lightrail', class: 'transit', subclass: 'light_rail', hasService: true },
	{ id: 'subway', class: 'transit', subclass: 'subway', hasService: true },
	{ id: 'narrowgauge', class: 'rail', subclass: 'narrow_gauge', hasService: true },
	{ id: 'tram', class: 'transit', subclass: 'tram', hasService: true },
	// Not observed in the sample; OpenMapTiles documents both as `transit` subclasses, and an unmatched
	// filter costs nothing where a missing one would lose the feature.
	{ id: 'funicular', class: 'transit', subclass: 'funicular', hasService: false },
	{ id: 'monorail', class: 'transit', subclass: 'monorail', hasService: false },
];

function buildStructures(): MaplibreLayerDefinition[] {
	return (['tunnel', 'street', 'bridge'] as const).flatMap((c): MaplibreLayerDefinition[] => {
		let filter: FilterSpecification[];
		let prefix: string;
		let suffixes: string[];

		switch (c) {
			case 'tunnel':
				filter = [['==', ['get', 'brunnel'], 'tunnel'] as FilterSpecification];
				prefix = 'tunnel-';
				suffixes = [':outline', ''];
				break;
			case 'street':
				filter = [
					['!=', ['get', 'brunnel'], 'bridge'] as FilterSpecification,
					['!=', ['get', 'brunnel'], 'tunnel'] as FilterSpecification,
				];
				prefix = '';
				suffixes = [':outline', ''];
				break;
			case 'bridge':
				filter = [['==', ['get', 'brunnel'], 'bridge'] as FilterSpecification];
				prefix = 'bridge-';
				suffixes = [':bridge', ':outline', ''];
				break;
		}

		const results: MaplibreLayerDefinition[] = [];
		const line = (id: string, ...clauses: FilterSpecification[]) =>
			results.push({
				id,
				type: 'line',
				'source-layer': 'transportation',
				filter: ['all', LINES, ...clauses, ...filter] as FilterSpecification,
			});

		// The bridge deck area: `class: bridge` polygons, where Shortbread reads a whole source-layer.
		// Emitted once (in the surface pass) as there, and carrying no `brunnel` clause — the deck *is* the
		// bridge, so it is not additionally flagged as one.
		if (c === 'street')
			results.push({
				id: 'bridge',
				type: 'fill',
				'source-layer': 'transportation',
				filter: ['all', AREAS, ['==', ['get', 'class'], 'bridge']] as FilterSpecification,
			});

		for (const suffix of suffixes) {
			if (suffix === ':outline')
				results.push({
					id: prefix + 'street-pedestrian-zone',
					type: 'fill',
					'source-layer': 'transportation',
					filter: [
						'all',
						AREAS,
						...filter,
						['==', ['get', 'class'], 'path'],
						['==', ['get', 'subclass'], 'pedestrian'],
					] as FilterSpecification,
				});

			for (const [id, subclass] of Object.entries(PATH_SUBCLASS)) {
				line(prefix + 'way-' + id + suffix, ['==', ['get', 'class'], 'path'], ['==', ['get', 'subclass'], subclass]);
			}

			// `minor` in place of Shortbread's residential / unclassified / livingstreet (finding 1);
			// `busguideway` has no OpenMapTiles class and is dropped.
			for (const t of ['track', 'pedestrian', 'service', 'minor', 'busway']) {
				if (t === 'pedestrian') {
					line(
						prefix + 'street-pedestrian' + suffix,
						['==', ['get', 'class'], 'path'],
						['==', ['get', 'subclass'], 'pedestrian']
					);
				} else {
					line(prefix + 'street-' + t + suffix, ['==', ['get', 'class'], t]);
				}
			}

			if (suffix === '')
				for (const t of ['track', 'pedestrian', 'service', 'minor']) {
					const classClauses: FilterSpecification[] =
						t === 'pedestrian'
							? [
									['==', ['get', 'class'], 'path'],
									['==', ['get', 'subclass'], 'pedestrian'],
								]
							: [['==', ['get', 'class'], t]];
					line(prefix + 'street-' + t + '-bicycle', ...classClauses, ['==', ['get', 'bicycle'], 'designated']);
				}

			// `link` is `ramp: 1` (finding 6).
			for (const t of ['tertiary', 'secondary', 'primary', 'trunk', 'motorway']) {
				line(prefix + 'street-' + t + '-link' + suffix, ['==', ['get', 'class'], t], ['==', ['get', 'ramp'], 1]);
			}
			for (const t of ['tertiary', 'secondary', 'primary', 'trunk', 'motorway']) {
				line(prefix + 'street-' + t + suffix, ['==', ['get', 'class'], t], ['!=', ['get', 'ramp'], 1]);
			}
		}

		for (const suffix of [':outline', ''] as const) {
			for (const rail of [...RAIL_TYPES].reverse()) {
				const pair: FilterSpecification[] = [
					['==', ['get', 'class'], rail.class],
					['==', ['get', 'subclass'], rail.subclass],
				];
				if (rail.hasService) {
					line(prefix + 'transport-' + rail.id + suffix, ...pair, ['!', ['has', 'service']]);
					line(prefix + 'transport-' + rail.id + '-service' + suffix, ...pair, ['has', 'service']);
				} else {
					line(prefix + 'transport-' + rail.id + suffix, ...pair);
				}
			}

			if (c === 'street') {
				// One layer, not nine plus a merge (finding 7). No `...filter`: the `brunnel` clauses were
				// always true for an aerialway in Shortbread's separate source-layer, and remain irrelevant.
				results.push({
					id: 'aerialway' + suffix,
					type: 'line',
					'source-layer': 'transportation',
					filter: ['all', LINES, ['==', ['get', 'class'], 'aerialway']] as FilterSpecification,
				});
				results.push({
					id: 'transport-ferry' + suffix,
					type: 'line',
					'source-layer': 'transportation',
					filter: ['all', LINES, ['==', ['get', 'class'], 'ferry']] as FilterSpecification,
				});
			}
		}

		return results;
	});
}

// ── Inline style resolution ────────────────────────────────────────────────────

type Prefix = '' | 'tunnel-' | 'bridge-';

// The old VersaTiles road widths: hand-tuned linear stops (no exponential base) that stay thin at
// low/mid zoom and ramp up steeply past z16, reaching their full chunky width at z19–20.
const MINOR_WIDTH = {
	outline: { 12: 2, 14: 3, 16: 6, 18: 26, 19: 64, 20: 128 },
	main: { 12: 1, 14: 2, 16: 5, 18: 24, 19: 60, 20: 120 },
};

// The arterial classes drawn in the yellow/orange palette. In the old VersaTiles style tertiary is
// NOT arterial — it's a white minor road — so it is deliberately absent here.
const YELLOW = new Set(['motorway', 'trunk', 'primary', 'secondary']);
const isServiceLike = (base: string): boolean => base === 'service' || base === 'busway';

// Appearance zoom per road class — the zoom each class first appears at, which roads blend in from 0
// width over. **Carried over from the Shortbread table, not measured**: confirming which classes exist
// took a dozen tiles, but confirming when each one starts needs a zoom sweep, which the value sample
// cannot give. These are therefore the module's least evidence-backed numbers.
const STREET_APPEAR: Record<string, number> = {
	motorway: 5,
	trunk: 6,
	primary: 8,
	secondary: 9,
	tertiary: 10,
	// `minor` stands for Shortbread's residential / unclassified / living_street, which appeared at 12,
	// 12 and 13 respectively; the earliest of the three is the honest choice for the merged class.
	minor: 12,
	busway: 12,
	pedestrian: 13,
	service: 13,
	track: 13,
};

function streetAppear(base: string, isLink: boolean): number {
	// The `link` flag is only populated from z11; OSM Bright renders motorway ramps from z12, the rest z13.
	if (isLink) return base === 'motorway' ? 12 : 13;
	return STREET_APPEAR[base] ?? 12;
}

// Line width by base street type — the old VersaTiles curves. These are identical across surface,
// tunnel and bridge (the old style never varied fill/casing width by prefix; only the bridge deck,
// handled in `bridgeDeckStyle`, differs), so `prefix` is not consulted here.
function streetWidth(base: string, isLink: boolean, isOutline: boolean): { size: b.SizeValue } {
	if (isLink) {
		// tertiary-link follows the minor curve; every other link shares a common (thinner) curve.
		if (base === 'tertiary') return { size: isOutline ? MINOR_WIDTH.outline : MINOR_WIDTH.main };
		return isOutline
			? { size: { 12: 2, 14: 3, 16: 7, 18: 14, 20: 40 } }
			: { size: { 12: 1, 14: 2, 16: 5, 18: 12, 20: 38 } };
	}
	switch (base) {
		case 'motorway':
			return isOutline
				? { size: { 5: 0, 6: 2, 10: 5, 14: 5, 16: 14, 18: 38, 19: 84, 20: 168 } }
				: { size: { 5: 0, 6: 1, 10: 4, 14: 4, 16: 12, 18: 36, 19: 80, 20: 160 } };
		case 'trunk':
			return isOutline
				? { size: { 6: 0, 7: 2, 10: 4, 14: 6, 16: 12, 18: 36, 19: 74, 20: 144 } }
				: { size: { 6: 0, 7: 1, 10: 3, 14: 5, 16: 10, 18: 34, 19: 70, 20: 140 } };
		case 'primary':
			return isOutline
				? { size: { 8: 0, 9: 1, 10: 4, 14: 6, 16: 12, 18: 36, 19: 74, 20: 144 } }
				: { size: { 8: 0, 9: 2, 10: 3, 14: 5, 16: 10, 18: 34, 19: 70, 20: 140 } };
		case 'secondary':
			return isOutline
				? { size: { 11: 2, 14: 5, 16: 8, 18: 30, 19: 68, 20: 138 } }
				: { size: { 11: 1, 14: 4, 16: 6, 18: 28, 19: 64, 20: 130 } };
		case 'service':
		case 'busway':
			return isOutline
				? { size: { 14: 1, 16: 3, 18: 12, 19: 32, 20: 48 } }
				: { size: { 14: 1, 16: 2, 18: 10, 19: 28, 20: 40 } };
		case 'track':
			return isOutline
				? { size: { 14: 2, 16: 4, 18: 18, 19: 48, 20: 96 } }
				: { size: { 14: 1, 16: 3, 18: 16, 19: 44, 20: 88 } };
		default: // tertiary / minor / pedestrian — the minor curve
			return { size: isOutline ? MINOR_WIDTH.outline : MINOR_WIDTH.main };
	}
}

// Surface fill (main) + casing (:outline) colors per class — the old VersaTiles road palette.
function classColors(c: LayerContext['c'], fg: Color, base: string): { main: Color; casing: Color } {
	if (base === 'motorway') return { main: c.roadMotorway, casing: c.roadMotorwayBg };
	if (YELLOW.has(base)) return { main: c.roadTrunk, casing: c.roadTrunkBg };
	// Pedestrian streets are drawn in the lavender foot color; service/bus in a faint off-white with a
	// slightly lighter casing. Everything else (tertiary / minor / track) is a plain white minor road
	// with the warm-grey street casing.
	if (base === 'pedestrian') return { main: c.transitFoot, casing: c.roadStreetBg };
	if (isServiceLike(base))
		return { main: c.roadStreet.blend(0.03, fg), casing: c.roadStreetBg.blend(0.3, c.roadStreet) };
	return { main: c.roadStreet, casing: c.roadStreetBg };
}

function streetLineStyle(ctx: LayerContext, prefix: Prefix, t: string, isOutline: boolean): b.StyleProps {
	const { c, fg } = ctx;
	const isLink = t.endsWith('-link');
	const base = isLink ? t.slice(0, -5) : t;
	const { main, casing } = classColors(c, fg, base);
	const isYellow = YELLOW.has(base);

	const r: b.StyleProps = { lineJoin, lineCap };

	if (isOutline) {
		r.color = casing;
		// Bridges lighten the white-minor / pedestrian casing to a neutral grey.
		if (prefix === 'bridge-' && !isYellow && !isServiceLike(base)) r.color = c.roadStreet.blend(0.15, fg);
	} else {
		r.color = main;
		// Pedestrian streets are lavender only on the surface; on bridges they render white.
		if (prefix === 'bridge-' && base === 'pedestrian') r.color = c.roadStreet;
	}

	Object.assign(r, streetWidth(base, isLink, isOutline));

	// Every road type fades in by opacity (0 → 1) over its Shortbread appearance zoom z → z+1, so it
	// materializes smoothly instead of popping. Applies to both the casing (:outline) and the fill.
	r.opacity = b.fadeIn(streetAppear(base, isLink));

	return r;
}

function zoneStyle(ctx: LayerContext, prefix: Prefix): b.StyleProps {
	const { c } = ctx;
	// The surface zone is a tint over what it covers — landuse, sites, the plaza's own paths — so it
	// fades in to 0.25, not to 1. At full strength it hides all of them; v5 expressed the same thing
	// as a 25%-alpha fill colour. Bridges and tunnels below are real surfaces, not tints, and stay opaque.
	if (prefix === '') return { color: c.transitFoot, opacity: { 14: 0, 15: 0.25 } };
	// Inside a tunnel or on a bridge the zone is a built deck, not a tint over the ground, so it takes
	// the road surface colour rather than the lavender. `underground` fades the tunnel one from here.
	return { color: c.roadStreet, opacity: { 12: 0, 13: 1 } };
}

function bicycleStyle(ctx: LayerContext, base: string): b.StyleProps {
	const { c } = ctx;
	const r: b.StyleProps = { lineJoin, lineCap };
	r.color = c.roadStreet;
	// minor width for these bicycle overlays (track/service overlays get none)
	if (base === 'minor' || base === 'pedestrian') {
		r.size = MINOR_WIDTH.main;
		r.opacity = { 12: 0, 13: 1 };
		r.color = c.transitCycle;
		r.lineCap = 'round';
	}
	return r;
}

// Path-class ways (footway/steps/path/cycleway), old VersaTiles style: a solid line with a matching
// casing, growing in from 0 width at z13. footway/steps/path use the lavender foot color; cycleway
// the light-blue cycle color. Tunnels dash the fill; bridges also get a deck (see bridgeDeckStyle).
function wayStyle(ctx: LayerContext, t: string, isOutline: boolean): b.StyleProps | null {
	const { c, fg } = ctx;
	const fill = t === 'cycleway' ? c.transitCycle : c.transitFoot;

	if (isOutline) {
		// Casing: the fill darkened ~10% (matches the old style's outline tint), solid in every prefix.
		return {
			color: fill.blend(0.1, fg),
			lineJoin,
			lineCap,
			size: { 13: 0, 16: 5, 18: 7, 19: 12, 20: 22 },
		};
	}
	return {
		color: fill,
		lineJoin,
		lineCap,
		size: { 13: 0, 16: 4, 18: 6, 19: 10, 20: 20 },
	};
}

// Returns null for variants that should not be drawn at all (e.g. ferry casing,
// service-track rail/subway/tram) so the caller skips them instead of emitting a bare layer.
function transportStyle(ctx: LayerContext, t: string, isOutline: boolean): b.StyleProps | null {
	const { c, fg, bg } = ctx;

	if (t === 'ferry')
		return isOutline
			? null
			: {
					minzoom: 10,
					// closest derivation of OSM Bright's ferry teal (#6c9fb6) from the single water color;
					// blend toward `fg` (black in light mode / white in dark mode) rather than absolute darken
					color: c.water.saturate(0.8).blend(0.3, fg),
					size: 1.1,
					opacity: { 10: 0, 11: 1 },
					lineDasharray: [2, 2],
					lineJoin, // OSM Bright: ferry cap butt (default) / join round
				};

	const isService = t.endsWith('-service');
	const rt = isService ? t.slice(0, -'-service'.length) : t;

	let r: b.StyleProps | null;
	if (rt === 'rail' || rt === 'lightrail') {
		// Old VersaTiles railway: a WIDE solid base line (:outline) with a slightly narrower, LIGHTER
		// `[2, 2]`-dashed "tie" line (fill) on top. The darker base shows through the gaps, giving the
		// alternating darker/lighter tie bands (rather than OSM Bright's thin cross-ticks).
		if (isService)
			r = isOutline
				? { color: c.transitRail, size: { 14: 0, 15: 1, 16: 1, 20: 14 } }
				: { color: c.transitRail.blend(0.3, bg), lineDasharray: [2, 2], size: { 15: 0, 16: 1, 20: 10 } };
		else
			r = isOutline
				? // The casing is a hairline well before its width ramp starts moving, so its fade-in is what
					// puts it on the map — and z11 is the earliest zoom at which putting it there is honest.
					//
					// Shortbread ships service tracks (yards, sidings, spurs, crossovers) from z10 but the
					// `service` attribute that identifies them only from z11, so at z10 a marshalling yard is
					// indistinguishable from a main line: at Maschen that is 270 km of track in one tile that
					// this layer would have to draw at full mainline weight. Below z10 the data is clean —
					// service tracks are simply absent — so z8/z9 would be safe, but appearing at z8, blooming
					// into a solid mass at z10 and thinning again at z11 is worse than starting at z11. If the
					// schema ever supplies `service` from z10, this can move back down.
					{
						color: c.transitRail,
						size: { 8: 1, 13: 1, 15: 1, 20: 14 },
						opacity: b.fadeIn(11),
					}
				: {
						color: c.transitRail.blend(0.3, bg),
						lineDasharray: [2, 2],
						size: { 14: 0, 15: 1, 20: 10 },
						opacity: b.fadeIn(14),
					};
	} else if (rt === 'subway') {
		if (isService) return null;
		// Subway: same two-tone tie technique in its own (bluer) grey. The casing joins the map at z11,
		// a city-overview zoom; the ties only make sense once the casing is wide enough to show them.
		r = isOutline
			? {
					color: c.transitSubway,
					size: { 11: 0, 12: 1, 15: 3, 16: 3, 18: 6, 19: 8, 20: 10 },
					opacity: b.fadeIn(11),
				}
			: {
					color: c.transitSubway.blend(0.3, bg),
					lineDasharray: [2, 2],
					size: { 11: 0, 12: 1, 15: 2, 16: 2, 18: 5, 19: 6, 20: 8 },
					opacity: b.fadeIn(14),
				};
	} else {
		// tram / narrowgauge / funicular / monorail
		if (isService) return null;
		// No opacity ramp here: both width curves already grow from 0 (the casing at z15, the track at
		// z13), which is the appearance transition — adding a fade on top would only dim the track
		// through the zooms where it is the sole thing drawn.
		r = isOutline
			? { color: c.transitRail, size: { 15: 0, 16: 5, 18: 7, 20: 20 }, lineDasharray: [0.1, 0.5] }
			: { size: { 13: 0, 16: 1, 17: 2, 18: 3, 20: 5 }, color: c.transitRail };
	}

	return r;
}

function bridgeDeckStyle(ctx: LayerContext, s: string): b.StyleProps {
	const { c, fg } = ctx;
	const base: b.StyleProps = {
		lineCap,
		lineJoin,
		color: c.land.blend(0.02, fg),
		fillAntialias: true,
		opacity: 0.5,
	};
	if (s.startsWith('way-')) return { ...base, size: { 15: 0, 16: 7, 18: 10, 19: 17, 20: 31 }, minzoom: 15 };

	const t = s.slice('street-'.length);
	const isLink = t.endsWith('-link');
	const bt = isLink ? t.slice(0, -5) : t;

	if (isLink) {
		if (bt === 'motorway') return { ...base, minzoom: 12, size: { 12: 3, 14: 4, 16: 10, 18: 20, 20: 56 } };
		if (bt === 'trunk' || bt === 'primary' || bt === 'secondary')
			return { ...base, minzoom: 13, size: { 12: 3, 14: 4, 16: 10, 18: 20, 20: 56 } };
		// tertiary-link → minor deck
		return { ...base, size: { 12: 3, 14: 4, 16: 8, 18: 36, 19: 90, 20: 179 }, opacity: { 12: 0, 13: 1 } };
	}
	switch (bt) {
		case 'motorway':
			return { ...base, size: { 5: 0, 6: 3, 10: 7, 14: 7, 16: 20, 18: 53, 19: 118, 20: 235 } };
		case 'trunk':
			return { ...base, size: { 7: 0, 8: 3, 10: 6, 14: 8, 16: 17, 18: 50, 19: 104, 20: 202 } };
		case 'primary':
			return { ...base, size: { 8: 0, 9: 1, 10: 6, 14: 8, 16: 17, 18: 50, 19: 104, 20: 202 } };
		case 'secondary':
			return { ...base, size: { 11: 3, 14: 7, 16: 11, 18: 42, 19: 95, 20: 193 }, opacity: { 11: 0, 12: 1 } };
		case 'tertiary':
		case 'minor':
		case 'pedestrian':
			return { ...base, size: { 12: 3, 14: 4, 16: 8, 18: 36, 19: 90, 20: 179 }, opacity: { 12: 0, 13: 1 } };
		case 'service':
		case 'track':
			return { ...base, size: { 14: 3, 16: 6, 18: 25, 19: 67, 20: 134 }, opacity: { 14: 0, 15: 1 } };
		default: // busway
			return base;
	}
}

// Compute the fully-resolved style for a road layer from its id.
// Returns the resolved style for a road layer, or null when the layer should not be
// drawn (no styling rule). Every non-null result carries a color, so the caller can
// safely treat it as a colored style for the mandatory-color fill/line builders.
function roadStyle(ctx: LayerContext, id: string): b.StyleProps | null {
	if (id === 'bridge') return { color: ctx.c.land.blend(0.02, ctx.fg), fillAntialias: true, opacity: 0.8 };

	let prefix: Prefix = '';
	let s = id;
	if (s.startsWith('tunnel-')) {
		prefix = 'tunnel-';
		s = s.slice(7);
	} else if (s.startsWith('bridge-')) {
		prefix = 'bridge-';
		s = s.slice(7);
	}

	let suffix: '' | ':outline' | ':bridge' = '';
	if (s.endsWith(':outline')) {
		suffix = ':outline';
		s = s.slice(0, -8);
	} else if (s.endsWith(':bridge')) {
		suffix = ':bridge';
		s = s.slice(0, -7);
	}

	if (suffix === ':bridge') return bridgeDeckStyle(ctx, s);
	if (s === 'aerialway' || s.startsWith('aerialway:')) {
		// Aerialways (cable cars / lifts), OSM Bright style: a thin solid base line (:outline)
		// with a wider dashed line on top (the fill) giving the cable-tick pattern.
		// OSM Bright caps cable-cars round and joins them miter.
		if (suffix === ':outline')
			return { color: ctx.c.transitRail, minzoom: 13, size: { base: 1, stops: { 11: 1, 19: 2.5 } }, lineCap };
		return {
			color: ctx.c.transitRail,
			minzoom: 13,
			size: { base: 1, stops: { 11: 3, 19: 5.5 } },
			lineDasharray: [2, 3],
			lineCap,
		};
	}
	if (s.startsWith('transport-')) return transportStyle(ctx, s.slice('transport-'.length), suffix === ':outline');
	if (s.startsWith('way-')) return wayStyle(ctx, s.slice('way-'.length), suffix === ':outline');
	if (s.startsWith('street-')) {
		const t = s.slice('street-'.length);
		if (t === 'pedestrian-zone') return zoneStyle(ctx, prefix);
		if (t.endsWith('-bicycle')) return bicycleStyle(ctx, t.slice(0, -'-bicycle'.length));
		return streetLineStyle(ctx, prefix, t, suffix === ':outline');
	}
	return null;
}

// ── Group tagging (mirrors the old groups.ts road membership) ──────────────────

function roadGroup(id: string): string | undefined {
	// `aerialway` is one layer here, not nine, so the id has no kind suffix to match on.
	if (id === 'aerialway' || id.startsWith('aerialway:')) return 'transit.aerialways';
	const s = id.replace(/^(tunnel-|bridge-)/, '');
	if (s.startsWith('transport-ferry')) return 'transit.ferries';
	if (s.startsWith('transport-')) return 'transit.rail';
	if (id === 'bridge') return 'roads.motorways';
	if (s.startsWith('way-steps')) return 'roads.steps';
	if (s.startsWith('way-footway')) return 'roads.footway';
	if (s.startsWith('way-')) return 'roads.paths';
	if (s.startsWith('street-')) {
		let t = s.slice('street-'.length).replace(/(:outline|:bridge)$/, '');
		t = t.replace(/-(link|bicycle|zone)$/, '');
		switch (t) {
			case 'motorway':
			case 'trunk':
				return 'roads.motorways';
			case 'primary':
			case 'secondary':
			case 'tertiary':
				return 'roads.highways';
			// `minor` carries residential, unclassified and living_street together, so the group a caller
			// names is still the concept it means — the group vocabulary is schema-neutral, the class is not.
			case 'minor':
				return 'roads.streets.residential';
			case 'service':
				return 'roads.streets.service';
			case 'pedestrian':
				return 'roads.streets.pedestrian';
			case 'track':
				return 'roads.streets.track';
			case 'busway':
				return 'roads.streets.bus';
		}
	}
	return undefined;
}

// ── Underground (tunnel) treatment ─────────────────────────────────────────────

// The one definition of "this is below ground". Every `tunnel-` layer is routed through
// `underground` by the assembler, so a road or path type added later cannot quietly miss it, and
// there is a single place to look when the treatment needs debugging or tuning.
const UNDERGROUND = {
	// How far a tunnel's colour is faded toward `bg` (white in light mode, black in dark). 0.45 is
	// where the arterials gain the most — ΔE 16 from their surface colour — while still staying ~17
	// clear of every other colour on the map; past ~0.5 the casings start to merge into the ground.
	//
	// KNOWN GAP: `roadStreet` IS `bg`, so a fade cannot move the white minor roads at all and they
	// read the same underground as on the surface. Only a cue that is not a colour can mark those —
	// a dashed fill does it, and is what the test below records as missing. See the exception list
	// there before assuming a road was simply forgotten.
	fade: 0.45,
	// Rail is the exception (see `underground`): it keeps the translucency the old style gave it.
	translucency: 0.5,
} as const;

/** Scale an opacity — a constant or a zoom ramp — by a factor, keeping its shape. */
function scaleOpacity(opacity: b.StyleProps['opacity'], factor: number): b.StyleProps['opacity'] {
	if (opacity === undefined) return factor;
	if (typeof opacity === 'number') return opacity * factor;
	return Object.fromEntries(Object.entries(opacity).map(([z, v]) => [Number(z), v * factor]));
}

/**
 * Apply the underground treatment to one already-styled tunnel layer.
 *
 * Nothing here is per road class: every tunnel layer fades, and rail additionally dims.
 *
 * If a dash is ever added back here, it must set `line-cap: 'butt'`. A round cap extends every dash
 * by half a line width at BOTH ends, so it closes any gap narrower than 1.0 line widths — that is
 * why the `[0.5, 0.25]` and `[1, 0.2]` tunnel dashes this style used to carry all rendered solid.
 */
function underground(ctx: LayerContext, id: string, s: b.StyleProps): b.StyleProps {
	const color = typeof s.color === 'object' ? s.color.blend(UNDERGROUND.fade, ctx.bg) : s.color;

	// Rail keeps the translucency it has always had; its casing and its ties dim together.
	if (id.startsWith('tunnel-transport-'))
		return { ...s, color, opacity: scaleOpacity(s.opacity, UNDERGROUND.translucency) };

	return { ...s, color };
}

export function* roads(ctx: LayerContext): Generator<b.TaggedLayer> {
	for (const def of buildStructures()) {
		// every road structure is a fill or line layer (never background)
		const d = def as { id: string; type: string; 'source-layer': string; filter?: FilterSpecification };
		const style = roadStyle(ctx, d.id);
		if (!style) continue; // no styling rule → don't emit a bare (black) layer
		// A bridge is a mid-road section that must join flush to the surface road at both ends, so its
		// line ends use butt caps (like the old VersaTiles style). Round caps would round off the bridge
		// end into a bulge that overlaps the road it continues, making one street look like two
		// overlapping outlined pieces. Surface and tunnel roads keep round caps.
		if (d.type === 'line' && d.id.startsWith('bridge-')) (style as b.StyleProps).lineCap = 'butt';
		// Depth is a property of the structure, not of the road class, so it is applied here in one
		// pass rather than branching inside every style function.
		const placed = d.id.startsWith('tunnel-') ? underground(ctx, d.id, style) : style;
		const make = d.type === 'fill' ? b.fill : b.line;
		// roadStyle guarantees a color for every non-null result (see its contract).
		yield make(d.id, {
			sourceLayer: d['source-layer'],
			filter: d.filter,
			...(placed as b.ColoredStyleProps),
			group: roadGroup(d.id),
		});
	}
}
