import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { gzipSync } from 'node:zlib';

/**
 * What actually ends up in the CDN bundle, measured rather than assumed.
 *
 * `src/browser.test.ts` checks the entry's exports and that it cannot even reach the tooling modules.
 * This checks the other half, which only the built artifact can answer: a module may be *reachable*
 * through a barrel and still contribute nothing, and — the case that caught us — a module may
 * contribute bytes after every one of its exports is gone, because it does work when it is evaluated.
 * `options/minimize.ts` built a constant by calling three resolvers; `lib/fontCovers.ts` froze a script
 * table. Tree-shaking removes unused bindings; it cannot remove a `freeze` that runs at import time.
 *
 * Every generated byte is attributed to the source file it came from, by walking the sourcemap the
 * build already emits.
 */

const BUNDLE = new URL('../release/versatiles-style/versatiles-style.js', import.meta.url);

/**
 * Source files that must contribute nothing, with the export that used to bring each one in.
 *
 * The first four drop out on their own: `browser.ts` does not export them, so nothing reaches them.
 * `v5-hints.ts` is different — `checkKeys` calls it on the unknown-key path, so tree-shaking cannot
 * touch it and the browser half of `rollup.config.js` stubs it out (`stubV5Hints`). It is listed here
 * because that stub is the only thing keeping it out: remove the plugin and this test is what says so.
 */
const MUST_BE_ABSENT = [
	['src/options/minimize.ts', 'minimizeOptions'],
	['src/api/code.ts', 'toCode'],
	['src/lib/fontCovers.ts', 'fontCovers and the script helpers'],
	['src/lib/fetchFontFaces.ts', 'fetchFontFaces'],
	['src/options/parts/v5-hints.ts', 'checkKeys, until the build stubbed it'],
] as const;

/**
 * A ratchet, not a target: set a little above what the bundle weighs today, so an accidental import
 * that pulls a whole subtree fails here instead of shipping. Lower it when the bundle gets smaller.
 */
const GZIP_CEILING = 33 * 1024;

const CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
const DIGITS = new Map([...CHARS].map((char, index) => [char, index]));

function decodeVLQ(segment: string): number[] {
	const values: number[] = [];
	let shift = 0;
	let value = 0;
	for (const char of segment) {
		const digit = DIGITS.get(char);
		if (digit === undefined) throw new Error(`bad VLQ character ${JSON.stringify(char)}`);
		value += (digit & 31) << shift;
		if (digit & 32) {
			shift += 5;
			continue;
		}
		values.push(value & 1 ? -(value >> 1) : value >> 1);
		shift = 0;
		value = 0;
	}
	return values;
}

/** Bytes of the bundle attributed to each source file, via the sourcemap's mappings. */
function bytesPerSource(code: string, map: { mappings: string; sources: string[] }): Map<string, number> {
	const lines = code.split('\n');
	const bytes = new Map<string, number>();
	let source = 0;
	map.mappings.split(';').forEach((lineMappings, lineNumber) => {
		if (!lineMappings) return;
		const line = lines[lineNumber] ?? '';
		let column = 0;
		const segments: { column: number; source: number | null }[] = [];
		for (const segment of lineMappings.split(',')) {
			if (!segment) continue;
			const fields = decodeVLQ(segment);
			column += fields[0];
			if (fields.length > 1) source += fields[1];
			segments.push({ column, source: fields.length > 1 ? source : null });
		}
		segments.sort((a, b) => a.column - b.column);
		segments.forEach((segment, index) => {
			if (segment.source === null) return;
			const end = index + 1 < segments.length ? segments[index + 1].column : line.length;
			const name = (map.sources[segment.source] ?? '?').replace(/^(\.\.\/)+/, '');
			bytes.set(name, (bytes.get(name) ?? 0) + Buffer.byteLength(line.slice(segment.column, end)));
		});
	});
	return bytes;
}

describe.skipIf(!existsSync(BUNDLE))('the built browser bundle', () => {
	const code = readFileSync(BUNDLE, 'utf8');
	const map = JSON.parse(readFileSync(`${BUNDLE.pathname}.map`, 'utf8')) as { mappings: string; sources: string[] };
	const bytes = bytesPerSource(code, map);

	it('attributes its bytes to real source files, so the checks below mean something', () => {
		// a positive control: a broken sourcemap walk would report nothing and pass every check
		expect(bytes.get('src/api/osm.ts') ?? 0).toBeGreaterThan(500);
		expect([...bytes.values()].reduce((sum, n) => sum + n, 0)).toBeGreaterThan(code.length * 0.9);
	});

	it.each(MUST_BE_ABSENT)('contains no byte of %s (it came in with %s)', (file) => {
		expect(bytes.get(file) ?? 0).toBe(0);
	});

	it('carries nothing from node_modules', () => {
		// the style spec is reached only through `import type`, and a value import would bundle it
		expect([...bytes.keys()].filter((file) => file.includes('node_modules'))).toStrictEqual([]);
	});

	it(`stays under ${(GZIP_CEILING / 1024).toFixed(0)} KB gzipped`, () => {
		expect(gzipSync(code, { level: 9 }).length).toBeLessThan(GZIP_CEILING);
	});
});
