import { SpriteConfig } from './lib/sprites.js';

const config: SpriteConfig = {
	ratios: [1, 2, 3, 4],
	spritesheets: {
		basics: {
		icon: {
			size: 22,
			names: [
				'airfield',
				'airport',
				'alcohol_shop',
				'art_gallery',
				'artwork',
				'atm',
				'bakery',
				'bank',
				'bar',
				'beauty',
				'beer',
				'beergarden',
				'bench',
				'beverages',
				'bicycle_share',
				'books',
				'bus',
				'butcher',
				'cafe',
				'car_rental',
				'car_wash',
				'castle',
				'cemetery',
				'chalet',
				'chemist',
				'cinema',
				'clothes',
				'college',
				'community',
				'defibrillator',
				'dentist',
				'doctor',
				'dog_park',
				'doityourself',
				'drinking_water',
				'drycleaning',
				'embassy',
				'emergency_phone',
				'fast_food',
				'fire_station',
				'florist',
				'fountain',
				'furniture',
				'garden_centre',
				'gift',
				'golf',
				'greengrocer',
				'hairdresser',
				'hardware',
				'historic',
				'hospital',
				'huntingstand',
				'hydrant',
				'icerink',
				'jewelry_store',
				'kiosk',
				'laundry',
				'library',
				'lighthouse',
				'marketplace',
				'monument',
				'newsagent',
				'nightclub',
				'nursinghome',
				'observation_tower',
				'optician',
				'outdoor',
				'pharmacy',
				'picnic_site',
				'pitch',
				'place_of_worship',
				'playground',
				'police',
					'post',
				'postbox',
				'prison',
					'rail',
				'rail_light',
				'rail_metro',
				'recycling',
				'restaurant',
				'school',
				'shelter',
				'shoes',
				'shop',
				'shrine',
				'sports',
				'stadium',
				'stationery',
				'surveillance',
				'swimming',
				'telephone',
				'theatre',
				'toilet',
				'town_hall',
				'toys',
				'travel_agent',
				'vendingmachine',
				'veterinary',
				'video',
				'viewpoint',
				'waste_basket',
				'watermill',
				'waterpark',
				'windmill',
				'zoo',
			],
		},
		marking: { size: 15, names: ['arrow'], },
		pattern: {
			useSDF: false,
				size: 16, names: ['hatched_thin', 'striped', 'warning'],
		},
		transport: {
				size: 22, names: ['tram', 'information'],
		},
	},
		symbols: {
			icon: {
				size: 22,
				names: [
					'animal_shelter',
					'aquarium',
					'bbq',
					'beach',
					'entrance1',
					'heart',
					'home',
					'information',
					'karaoke',
					'mountain',
					'mushroom',
					'music',
					'park',
					'park1',
					'roadblock',
					'rocket',
					'water',
				]
			},
			symbol: {
				size: 22,
				names: [
					'arrow',
					'arrow1',
					'arrow2',
					'circle',
					'circle_outline',
					'cross',
					'cross_outline',
					'diamond',
					'diamond_outline',
					'hexagon',
					'hexagon_outline',
					'marker',
					'marker_outline',
					'square',
					'square_outline',
					'star',
					'star_outline',
					'triangle',
					'triangle_outline',
					'x',
					'x_outline',
				]
			}
		}
	}
};

export default config;