import { SpriteConfig } from './lib/sprites.js';

// Sprite name ↔ source file are deliberately decoupled. Files under `icons/` are organized by
// PROVENANCE and keep their upstream filename (`maki/alcohol-shop`, hyphen and all), so it stays
// obvious where an icon came from and whether we already have it. The sprite name — the public
// `<sheet>:<group>-<name>` id, which follows the naming convention in SPRITES.md — is assigned
// here. Icons drawn for this project live under `versatiles/`; `unknown/` is provenance we have not
// established yet (see icons/unknown/source.json). `npm run icons-report` renders the whole set.
//
// An entry is either a bare source path or an object, so metadata can be added per icon later:
//   cat: 'maki/animal-shelter',
//   cat: { src: 'maki/animal-shelter', tags: ['pet', 'animal'], description: 'A sitting cat' },
const config: SpriteConfig = {
	// 1x + 2x only: MapLibre fetches `base` (dpr ≤ 1) or `base@2x` (dpr > 1) and never @3x/@4x, and
	// the icons are SDF (resolution-independent), so higher ratios would be built but never used.
	ratios: [1, 2],
	spritesheets: {
		base: {
			icon: {
				size: 22,
				icons: {
					airfield: 'maki/airfield',
					airport: 'maki/airport',
					alcohol_shop: 'maki/alcohol-shop',
					amusement_park: 'maki/amusement-park',
					art_gallery: 'maki/art-gallery',
					artwork: 'versatiles/artwork',
					atm: 'unknown/atm',
					bakery: 'maki/bakery',
					bank: 'maki/bank',
					bar: 'maki/bar',
					beauty: 'versatiles/beauty',
					pint_glass: 'unknown/pint_glass',
					beer_mug: 'unknown/beer_mug',
					bench: 'versatiles/bench',
					beverages: 'versatiles/beverages',
					bicycle_share: 'maki/bicycle-share',
					books: 'versatiles/books',
					bus: 'unknown/bus',
					butcher: 'versatiles/butcher',
					cafe: 'maki/cafe',
					campsite: 'maki/campsite',
					car_rental: 'maki/car-rental',
					car_wash: 'unknown/car_wash',
					caravan: 'unknown/caravan',
					castle: 'maki/castle',
					cemetery: 'maki/cemetery',
					chalet: 'unknown/chalet',
					tube_and_toothbrush: 'unknown/tube_and_toothbrush',
					cinema: 'maki/cinema',
					clothes: 'versatiles/clothes',
					college: 'maki/college',
					community: 'unknown/community',
					defibrillator: 'maki/defibrillator',
					dentist: 'maki/dentist',
					dharma_wheel: 'maki/religious-buddhist',
					doctor: 'maki/doctor',
					dog: 'unknown/dog',
					do_it_yourself: 'versatiles/do_it_yourself',
					drinking_water: 'maki/drinking-water',
					dry_cleaning: 'versatiles/dry_cleaning',
					embassy: 'maki/embassy',
					emergency_access: 'versatiles/emergency_access',
					emergency_phone: 'maki/emergency-phone',
					fast_food: 'maki/fast-food',
					fire_station: 'maki/fire-station',
					florist: 'maki/florist',
					fountain: 'unknown/fountain',
					fuel_pump: 'unknown/fuel_pump',
					furniture: 'maki/furniture',
					garden_center: 'maki/garden-centre',
					gift: 'maki/gift',
					golf: 'maki/golf',
					greengrocer: 'versatiles/greengrocer',
					scissors_and_comb: 'temaki/beauty_salon',
					hardware: 'maki/hardware',
					historic: 'maki/historic',
					hospital: 'maki/hospital',
					hunting_stand: 'versatiles/hunting_stand',
					hydrant: 'temaki/fire_hydrant',
					ice_rink: 'versatiles/ice_rink',
					ring: 'unknown/ring',
					justice: 'unknown/justice',
					khanda: 'temaki/sikhism',
					latin_cross: 'maki/religious-christian',
					newspaper: 'unknown/newspaper',
					laundry: 'maki/laundry',
					library: 'maki/library',
					lighthouse: 'maki/lighthouse',
					lodging: 'maki/lodging',
					marketplace: 'versatiles/marketplace',
					monument: 'maki/monument',
					newsagent: 'versatiles/newsagent',
					nightclub: 'unknown/nightclub',
					nursing_home: 'versatiles/nursing_home',
					observation_tower: 'maki/observation-tower',
					om: 'temaki/hinduism',
					optician: 'maki/optician',
					outdoor: 'versatiles/outdoor',
					person_kneeling_and_praying: 'unknown/person_kneeling_and_praying',
					pill: 'unknown/pill',
					picnic_site: 'maki/picnic-site',
					pitch: 'maki/pitch',
					seesaw: 'temaki/seesaw',
					police_officer: 'temaki/police_officer',
					post: 'maki/post',
					postbox: 'versatiles/postbox',
					prison: 'maki/prison',
					rail: 'maki/rail',
					recycling: 'unknown/recycling',
					restaurant: 'maki/restaurant',
					school: 'maki/school',
					shelter: 'unknown/shelter',
					shoes: 'versatiles/shoes',
					shop: 'maki/shop',
					shrine: 'versatiles/shrine',
					sports: 'versatiles/sports',
					stadium: 'maki/stadium',
					star_and_crescent: 'maki/religious-muslim',
					star_of_david: 'unknown/star_of_david',
					stationery: 'versatiles/stationery',
					surveillance: 'versatiles/surveillance',
					swimming: 'maki/swimming',
					telephone: 'maki/telephone',
					theater: 'maki/theatre',
					restrooms: 'unknown/restrooms',
					town_hall: 'maki/town-hall',
					rocking_horse: 'unknown/rocking_horse',
					travel_agent: 'versatiles/travel_agent',
					vending_machine: 'unknown/vending_machine',
					veterinary: 'maki/veterinary',
					video: 'versatiles/video',
					viewpoint: 'maki/viewpoint',
					waste_basket: 'maki/waste-basket',
					wastewater: 'versatiles/wastewater',
					watermill: 'maki/watermill',
					water_park: 'versatiles/water_park',
					waterworks: 'versatiles/waterworks',
					windmill: 'maki/windmill',
					yin_yang: 'temaki/taoism',
					zoo: 'maki/zoo',
				},
			},
			marking: {
				size: 15,
				icons: {
					oneway: 'versatiles/oneway',
				},
			},
			pattern: {
				useSDF: false,
				size: 16,
				icons: {
					hatched_thin: 'versatiles/hatched_thin',
					striped: 'versatiles/striped',
					warning: 'versatiles/warning',
				},
			},
			transport: {
				size: 22,
				icons: {
					tram: 'unknown/tram',
					information: 'versatiles/information',
				},
			},
		},
		extras: {
			icon: {
				size: 22,
				icons: {
					bbq: 'maki/bbq',
					beach: 'maki/beach',
					cat: 'maki/animal-shelter',
					conifer: 'maki/park-alt1',
					droplet: 'maki/water',
					fish: 'maki/aquarium',
					house: 'maki/home',
					microphone: 'maki/karaoke',
					mountain: 'maki/mountain',
					mushroom: 'versatiles/mushroom',
					music: 'maki/music',
					no_entry: 'maki/roadblock',
					rocket: 'maki/rocket',
					tree: 'maki/park',
				},
			},
			// Map pins, drawn 24×30 with the tip ON the bottom edge so `icon-anchor: "bottom"` puts
			// the point on the coordinate. `size` is the rendered HEIGHT; the width follows from the
			// source aspect ratio (see Sprite.fromIcons):
			//   round(28 × 24/30) = round(22.4) = 22  →  22×28 on the sheet.
			// A source at a different aspect silently changes that width — config-sprites.test.ts
			// guards it.
			pin: {
				size: 28,
				icons: {
					balloon: 'versatiles/balloon',
					balloon_outline: 'versatiles/balloon_outline',
					teardrop: 'versatiles/teardrop',
					teardrop_1: 'versatiles/teardrop_1',
					teardrop_2: 'versatiles/teardrop_2',
					teardrop_3: 'versatiles/teardrop_3',
					teardrop_4: 'versatiles/teardrop_4',
					teardrop_5: 'versatiles/teardrop_5',
					teardrop_6: 'versatiles/teardrop_6',
					teardrop_7: 'versatiles/teardrop_7',
					teardrop_8: 'versatiles/teardrop_8',
					teardrop_9: 'versatiles/teardrop_9',
					teardrop_dot: 'versatiles/teardrop_dot',
					teardrop_hole: 'versatiles/teardrop_hole',
					teardrop_outline: 'versatiles/teardrop_outline',
				},
			},
			symbol: {
				size: 22,
				icons: {
					arrow: 'maki/arrow',
					arrow2: 'unknown/arrow2',
					arrow3: 'unknown/arrow3',
					arrow_circle: 'versatiles/arrow_circle',
					arrow_curved: 'versatiles/arrow_curved',
					arrow_double: 'versatiles/arrow_double',
					arrow_return: 'versatiles/arrow_return',
					caret: 'versatiles/caret',
					chart_bar: 'versatiles/chart_bar',
					chart_line: 'versatiles/chart_line',
					chart_pie: 'versatiles/chart_pie',
					check: 'versatiles/check',
					chevron: 'versatiles/chevron',
					chevron_double: 'versatiles/chevron_double',
					circle: 'versatiles/circle',
					circle_outline: 'versatiles/circle_outline',
					cross: 'versatiles/cross',
					cross_outline: 'versatiles/cross_outline',
					crosshair: 'versatiles/crosshair',
					diamond: 'versatiles/diamond',
					diamond_outline: 'versatiles/diamond_outline',
					dot: 'versatiles/dot',
					drop: 'versatiles/drop',
					drop_outline: 'versatiles/drop_outline',
					entrance: 'maki/entrance-alt1',
					exclamation: 'versatiles/exclamation',
					heart: 'maki/heart',
					heart_outline: 'versatiles/heart_outline',
					hexagon: 'versatiles/hexagon',
					hexagon_outline: 'versatiles/hexagon_outline',
					minus: 'versatiles/minus',
					number_0: 'versatiles/number_0',
					number_0_outline: 'versatiles/number_0_outline',
					number_1: 'versatiles/number_1',
					number_1_outline: 'versatiles/number_1_outline',
					number_2: 'versatiles/number_2',
					number_2_outline: 'versatiles/number_2_outline',
					number_3: 'versatiles/number_3',
					number_3_outline: 'versatiles/number_3_outline',
					number_4: 'versatiles/number_4',
					number_4_outline: 'versatiles/number_4_outline',
					number_5: 'versatiles/number_5',
					number_5_outline: 'versatiles/number_5_outline',
					number_6: 'versatiles/number_6',
					number_6_outline: 'versatiles/number_6_outline',
					number_7: 'versatiles/number_7',
					number_7_outline: 'versatiles/number_7_outline',
					number_8: 'versatiles/number_8',
					number_8_outline: 'versatiles/number_8_outline',
					number_9: 'versatiles/number_9',
					number_9_outline: 'versatiles/number_9_outline',
					octagon: 'versatiles/octagon',
					octagon_outline: 'versatiles/octagon_outline',
					oval: 'versatiles/oval',
					oval_outline: 'versatiles/oval_outline',
					pentagon: 'versatiles/pentagon',
					pentagon_outline: 'versatiles/pentagon_outline',
					percent: 'versatiles/percent',
					question: 'versatiles/question',
					rounded_square: 'versatiles/rounded_square',
					rounded_square_outline: 'versatiles/rounded_square_outline',
					slash: 'versatiles/slash',
					square: 'versatiles/square',
					square_outline: 'versatiles/square_outline',
					star: 'versatiles/star',
					star4: 'versatiles/star4',
					star4_outline: 'versatiles/star4_outline',
					star6: 'versatiles/star6',
					star6_outline: 'versatiles/star6_outline',
					star_outline: 'versatiles/star_outline',
					trend_down: 'versatiles/trend_down',
					trend_up: 'versatiles/trend_up',
					triangle: 'versatiles/triangle',
					triangle_outline: 'versatiles/triangle_outline',
					x: 'versatiles/x',
					x_outline: 'versatiles/x_outline',
				},
			},
		},
	},
};

export default config;
