/**
 * Regenerate the nine derived themes in src/themes from `colorful` — see scripts/lib/theme-generator.ts.
 *
 *   npm run generate-themes               # write the tables, listing what changed
 *   npm run generate-themes -- --dry-run  # only list what would change
 *   npm run generate-themes -- --report   # also print key contrasts for all ten themes
 *
 * Writes `src/themes/tables.ts` whole — the nine derived tables, one encoded string each. The tenth,
 * `colorful`, is the hand-written reference in `src/themes/colorful.ts` and is never touched here. Tune
 * a derived theme through its settings or OVERRIDES in the generator, not in the tables: a unit test
 * fails when the two disagree.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { colorOptionsKeys, type Palette, type ResolvedColors } from '../src/options/index.js';
import { getPaletteColors, PALETTES } from '../src/themes/index.js';
import { contrast, generateThemes, oklabDistance, over, parse, THEMES } from './lib/theme-generator.js';

const FILE = resolve(fileURLToPath(import.meta.url), '../../src/themes/tables.ts');
const args = process.argv.slice(2);
const generated = generateThemes();

let changes = 0;
for (const [name, colors] of Object.entries(generated)) {
	const current = getPaletteColors(name as Palette) as Record<string, string>;
	const changed = Object.entries(colors).filter(([key, value]) => current[key] !== value);
	if (changed.length === 0) continue;
	changes += changed.length;
	const largest = Math.max(...changed.map(([key, value]) => oklabDistance(current[key], value)));
	console.log(`${name}: ${changed.length} colour(s) change, largest OKLab distance ${largest.toFixed(3)}`);
}
if (changes === 0) console.log('All derived themes are up to date.');

if (changes > 0 && !args.includes('--dry-run')) {
	writeFileSync(FILE, tablesFile(generated));
	console.log('Wrote src/themes/tables.ts. Review the effect with `npm run compare -- --baseline`.');
}

if (args.includes('--report')) report();

/**
 * `src/themes/tables.ts`: one line per derived palette, holding its 45 colours in `colorOptionsKeys`
 * order, comma-separated and without the `#`.
 *
 * Encoded rather than spelled out because these nine tables are machine-written and machine-checked —
 * nobody reads them, and as object literals the repeated key names cost 5.4 KB of the browser bundle.
 * `getPaletteColors` decodes them; `src/themes/themes.test.ts` checks the round trip.
 */
function tablesFile(themes: Partial<Record<Palette, ResolvedColors>>): string {
	const rows = PALETTES.filter((palette) => palette !== 'colorful').map((palette) => {
		const colors = themes[palette] ?? (getPaletteColors(palette) as Record<string, string>);
		const missing = colorOptionsKeys.filter((key) => !/^#[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$/.test(colors[key] ?? ''));
		if (missing.length > 0) throw new Error(`${palette}: not a plain hex colour: ${missing.join(', ')}`);
		return `\t'${palette}':\n\t\t'${colorOptionsKeys.map((key) => colors[key].slice(1)).join(',')}',`;
	});
	return `// Generated by \`npm run generate-themes\` — do not edit. See scripts/generate-themes.ts.
//
// One line per derived palette: the colours of \`colorOptionsKeys\`, in that order, without their '#'.
// The tenth palette, \`colorful\`, is the hand-written reference in ./colorful.ts.

import type { Palette } from '../options/index.js';

export const TABLES: Record<Exclude<Palette, 'colorful'>, string> = {
${rows.join('\n')}
};
`;
}

function report(): void {
	const pairs: [string, string, string][] = [
		['label/land', 'label', 'land'],
		['labelWater/water', 'labelWater', 'water'],
		['street/land', 'roadStreet', 'land'],
		['streetBg/land', 'roadStreetBg', 'land'],
		['street/streetBg', 'roadStreet', 'roadStreetBg'],
		['motorway/land', 'roadMotorway', 'land'],
		['rail/land', 'transitRail', 'land'],
		['water/land', 'water', 'land'],
		['building/land', 'building', 'land'],
		['wood/land', 'natureWood', 'land'],
		['glacier/land', 'glacier', 'land'],
		['boundary/land', 'boundary', 'land'],
	];
	const themes = Object.keys(THEMES).flatMap((p) => [p, `${p}-dark`]) as Palette[];
	console.log('\nSigned contrast: above 1 lighter than the background, below 1 darker.\n');
	console.log('pair'.padEnd(18) + themes.map((t) => t.padEnd(15)).join(''));
	for (const [label, fg, bg] of pairs) {
		const cells = themes.map((theme) => {
			const colors = (generated[theme] ?? getPaletteColors(theme)) as Record<string, string>;
			const land = parse(colors.land);
			const background = bg === 'land' ? land : over(parse(colors[bg]), land);
			return contrast(parse(colors[fg]), background).toFixed(2).padEnd(15);
		});
		console.log(label.padEnd(18) + cells.join(''));
	}
}
