/**
 * The Protomaps Basemap schema, read from the daily planet build's PMTiles metadata — Protomaps
 * publishes no TileJSON, so the schema lives inside the archive. Prose specification:
 * https://docs.protomaps.com/basemaps/layers
 *
 * Attribution required by the tileset: "© OpenStreetMap contributors, © Protomaps".
 *
 * Two things set this schema apart from the others: it reaches z15 where Shortbread and
 * OpenMapTiles stop at z14, and it classifies with `kind` / `kind_detail` rather than
 * `class` / `subclass`.
 *
 * Generated from https://build.protomaps.com/20260913.pmtiles v4.15.2
 * by `npm run vendor-schema`. Do not edit by hand; re-run the script instead, and use
 * `npm run vendor-schema -- <name> --check` to find out whether this file has gone stale.
 */
export type ProtomapsLayer = { minzoom: number; maxzoom: number; fields: readonly string[] };

export const PROTOMAPS_SCHEMA: Readonly<Record<string, ProtomapsLayer>> = {
	boundaries: { minzoom: 0, maxzoom: 15, fields: ['brk_a3', 'disputed', 'kind', 'kind_detail', 'sort_rank'] },
	buildings: {
		minzoom: 11,
		maxzoom: 15,
		fields: ['addr_housenumber', 'height', 'kind', 'kind_detail', 'layer', 'min_height', 'sort_rank'],
	},
	earth: {
		minzoom: 0,
		maxzoom: 15,
		fields: [
			'kind',
			'min_zoom',
			'name',
			'name2',
			'name3',
			'name:ar',
			'name:bg',
			'name:cs',
			'name:da',
			'name:de',
			'name:el',
			'name:en',
			'name:es',
			'name:et',
			'name:fa',
			'name:fi',
			'name:fr',
			'name:ga',
			'name:he',
			'name:hi',
			'name:hr',
			'name:hu',
			'name:id',
			'name:it',
			'name:ja',
			'name:ko',
			'name:lt',
			'name:lv',
			'name:mr',
			'name:mt',
			'name:ne',
			'name:nl',
			'name:no',
			'name:pl',
			'name:pt',
			'name:ro',
			'name:ru',
			'name:sk',
			'name:sl',
			'name:sv',
			'name:tr',
			'name:uk',
			'name:ur',
			'name:vi',
			'name:zh-Hans',
			'name:zh-Hant',
			'pgf:name:hi',
			'pgf:name:mr',
			'pgf:name:ne',
			'script',
			'script2',
			'script3',
		],
	},
	landcover: { minzoom: 0, maxzoom: 7, fields: ['kind'] },
	landuse: { minzoom: 2, maxzoom: 15, fields: ['kind', 'sort_rank'] },
	places: {
		minzoom: 1,
		maxzoom: 15,
		fields: [
			'capital',
			'kind',
			'kind_detail',
			'min_zoom',
			'name',
			'name2',
			'name3',
			'name:ar',
			'name:bg',
			'name:cs',
			'name:da',
			'name:de',
			'name:el',
			'name:en',
			'name:es',
			'name:et',
			'name:fa',
			'name:fi',
			'name:fr',
			'name:ga',
			'name:he',
			'name:hi',
			'name:hr',
			'name:hu',
			'name:id',
			'name:it',
			'name:ja',
			'name:ko',
			'name:lt',
			'name:lv',
			'name:mr',
			'name:mt',
			'name:ne',
			'name:nl',
			'name:no',
			'name:pl',
			'name:pt',
			'name:ro',
			'name:ru',
			'name:sk',
			'name:sl',
			'name:sv',
			'name:tr',
			'name:uk',
			'name:ur',
			'name:vi',
			'name:zh-Hans',
			'name:zh-Hant',
			'pgf:name',
			'pgf:name2',
			'pgf:name:en',
			'pgf:name:hi',
			'pgf:name:mr',
			'pgf:name:ne',
			'population',
			'population_rank',
			'ref',
			'ref:FR:FANTOIR',
			'ref:FR:SIREN',
			'ref:RS:nkd',
			'ref:SE:pts:postort',
			'ref:USCG',
			'ref:USPS',
			'ref:assessors_office',
			'ref:catasto',
			'ref:category',
			'ref:en',
			'ref:gdke',
			'ref:lzh',
			'ref:nan',
			'ref:nan-Hans',
			'ref:nan-Hant',
			'ref:nan-Latn-pehoeji',
			'ref:nan-Latn-tailo',
			'ref:nid',
			'ref:nuts:1',
			'ref:nuts:2',
			'ref:vi',
			'ref:whc',
			'ref:xpcc',
			'ref:zh',
			'ref:zh-Hans',
			'ref:zh-Hant',
			'script',
			'script2',
			'script3',
			'sort_key',
			'wikidata',
		],
	},
	pois: {
		minzoom: 5,
		maxzoom: 15,
		fields: [
			'elevation',
			'iata',
			'kind',
			'kind_detail',
			'min_zoom',
			'name',
			'name2',
			'name3',
			'name:ar',
			'name:bg',
			'name:cs',
			'name:da',
			'name:de',
			'name:el',
			'name:en',
			'name:es',
			'name:et',
			'name:fa',
			'name:fi',
			'name:fr',
			'name:ga',
			'name:he',
			'name:hi',
			'name:hr',
			'name:hu',
			'name:id',
			'name:it',
			'name:ja',
			'name:ko',
			'name:lt',
			'name:lv',
			'name:mr',
			'name:mt',
			'name:ne',
			'name:nl',
			'name:no',
			'name:pl',
			'name:pt',
			'name:ro',
			'name:ru',
			'name:sk',
			'name:sl',
			'name:sv',
			'name:tr',
			'name:uk',
			'name:ur',
			'name:vi',
			'name:zh-Hans',
			'name:zh-Hant',
			'pgf:name',
			'pgf:name2',
			'pgf:name3',
			'pgf:name:en',
			'pgf:name:fa',
			'pgf:name:he',
			'pgf:name:hi',
			'pgf:name:mr',
			'pgf:name:ne',
			'script',
			'script2',
			'script3',
		],
	},
	roads: {
		minzoom: 3,
		maxzoom: 15,
		fields: [
			'access',
			'is_bridge',
			'is_link',
			'is_tunnel',
			'kind',
			'kind_detail',
			'min_zoom',
			'name',
			'name2',
			'name3',
			'name:ar',
			'name:bg',
			'name:cs',
			'name:da',
			'name:de',
			'name:el',
			'name:en',
			'name:es',
			'name:et',
			'name:fa',
			'name:fi',
			'name:fr',
			'name:ga',
			'name:he',
			'name:hi',
			'name:hr',
			'name:hu',
			'name:id',
			'name:it',
			'name:ja',
			'name:ko',
			'name:lt',
			'name:lv',
			'name:mr',
			'name:mt',
			'name:ne',
			'name:nl',
			'name:no',
			'name:pl',
			'name:pt',
			'name:ro',
			'name:ru',
			'name:sk',
			'name:sl',
			'name:sv',
			'name:tr',
			'name:uk',
			'name:ur',
			'name:vi',
			'name:zh-Hans',
			'name:zh-Hant',
			'network',
			'network_1',
			'network_2',
			'network_3',
			'network_4',
			'network_5',
			'network_6',
			'oneway',
			'pgf:name',
			'pgf:name2',
			'pgf:name:en',
			'pgf:name:hi',
			'pgf:name:mr',
			'pgf:name:ne',
			'ref',
			'route',
			'script',
			'script2',
			'script3',
			'service',
			'shield_text',
			'shield_text_1',
			'shield_text_2',
			'shield_text_3',
			'shield_text_4',
			'shield_text_5',
			'shield_text_6',
			'sort_rank',
		],
	},
	water: {
		minzoom: 0,
		maxzoom: 15,
		fields: [
			'bridge',
			'kind',
			'kind_detail',
			'layer',
			'min_zoom',
			'name',
			'name2',
			'name3',
			'name:ar',
			'name:bg',
			'name:cs',
			'name:da',
			'name:de',
			'name:el',
			'name:en',
			'name:es',
			'name:et',
			'name:fa',
			'name:fi',
			'name:fr',
			'name:ga',
			'name:he',
			'name:hi',
			'name:hr',
			'name:hu',
			'name:id',
			'name:it',
			'name:ja',
			'name:ko',
			'name:lt',
			'name:lv',
			'name:mr',
			'name:mt',
			'name:ne',
			'name:nl',
			'name:no',
			'name:pl',
			'name:pt',
			'name:ro',
			'name:ru',
			'name:sk',
			'name:sl',
			'name:sv',
			'name:tr',
			'name:uk',
			'name:ur',
			'name:vi',
			'name:zh-Hans',
			'name:zh-Hant',
			'pgf:name',
			'pgf:name2',
			'pgf:name:en',
			'pgf:name:hi',
			'pgf:name:mr',
			'pgf:name:ne',
			'script',
			'script2',
			'script3',
			'sort_rank',
			'tunnel',
		],
	},
};
