/**
 * The Shortbread schema as the VersaTiles OSM tileset actually implements it: the `vector_layers`
 * block of https://tiles.versatiles.org/tiles/osm/tiles.json, which states which source-layers
 * exist, at which zooms, and what fields each carries.
 *
 * Vendored so the style can gate layers at the zoom their data begins (see `applyDataFloor`) and so
 * `schema.test.ts` can check offline that the style only asks for data that exists. Refresh from
 * that URL when the tileset changes. Prose specification:
 * https://shortbread-tiles.org/schema/1.1/
 */
export type ShortbreadLayer = { minzoom: number; maxzoom: number; fields: readonly string[] };

export const SHORTBREAD_SCHEMA: Readonly<Record<string, ShortbreadLayer>> = {
	addresses: { minzoom: 14, maxzoom: 14, fields: ['block', 'housename', 'housenumber', 'unit'] },
	aerialways: { minzoom: 12, maxzoom: 14, fields: ['kind'] },
	boundaries: { minzoom: 0, maxzoom: 14, fields: ['admin_level', 'disputed', 'maritime'] },
	boundary_labels: {
		minzoom: 2,
		maxzoom: 14,
		fields: [
			'admin_level',
			'name',
			'name_ar',
			'name_de',
			'name_el',
			'name_en',
			'name_es',
			'name_fr',
			'name_it',
			'name_nl',
			'name_pl',
			'name_pt',
			'name_uk',
			'way_area',
		],
	},
	bridges: {
		minzoom: 12,
		maxzoom: 14,
		fields: [
			'kind',
			'name',
			'name_ar',
			'name_de',
			'name_el',
			'name_en',
			'name_es',
			'name_fr',
			'name_it',
			'name_nl',
			'name_pl',
			'name_pt',
			'name_uk',
		],
	},
	buildings: { minzoom: 14, maxzoom: 14, fields: ['dummy', 'height', 'hide_3d', 'min_height'] },
	dam_lines: { minzoom: 12, maxzoom: 14, fields: ['kind'] },
	dam_polygons: { minzoom: 12, maxzoom: 14, fields: ['kind'] },
	ferries: {
		minzoom: 10,
		maxzoom: 14,
		fields: [
			'kind',
			'name',
			'name_ar',
			'name_de',
			'name_el',
			'name_en',
			'name_es',
			'name_fr',
			'name_it',
			'name_nl',
			'name_pl',
			'name_pt',
			'name_uk',
		],
	},
	land: { minzoom: 0, maxzoom: 14, fields: ['kind'] },
	ocean: { minzoom: 0, maxzoom: 14, fields: [] },
	pier_lines: { minzoom: 12, maxzoom: 14, fields: ['kind'] },
	pier_polygons: { minzoom: 12, maxzoom: 14, fields: ['kind'] },
	place_labels: {
		minzoom: 4,
		maxzoom: 14,
		fields: [
			'kind',
			'name',
			'name_ar',
			'name_de',
			'name_el',
			'name_en',
			'name_es',
			'name_fr',
			'name_it',
			'name_nl',
			'name_pl',
			'name_pt',
			'name_uk',
			'population',
		],
	},
	pois: {
		minzoom: 14,
		maxzoom: 14,
		fields: [
			'amenity',
			'atm',
			'cuisine',
			'denomination',
			'emergency',
			'highway',
			'historic',
			'housename',
			'housenumber',
			'information',
			'leisure',
			'man_made',
			'name',
			'name_ar',
			'name_de',
			'name_el',
			'name_en',
			'name_es',
			'name_fr',
			'name_it',
			'name_nl',
			'name_pl',
			'name_pt',
			'name_uk',
			'office',
			'recycling:clothes',
			'recycling:glass_bottles',
			'recycling:paper',
			'recycling:scrap_metal',
			'religion',
			'shop',
			'sport',
			'tourism',
			'tower:type',
			'vending',
		],
	},
	public_transport: {
		minzoom: 11,
		maxzoom: 14,
		fields: [
			'iata',
			'kind',
			'name',
			'name_ar',
			'name_de',
			'name_el',
			'name_en',
			'name_es',
			'name_fr',
			'name_it',
			'name_nl',
			'name_pl',
			'name_pt',
			'name_uk',
		],
	},
	sites: { minzoom: 14, maxzoom: 14, fields: ['kind'] },
	street_labels: {
		minzoom: 10,
		maxzoom: 14,
		fields: [
			'kind',
			'name',
			'name_ar',
			'name_de',
			'name_el',
			'name_en',
			'name_es',
			'name_fr',
			'name_it',
			'name_nl',
			'name_pl',
			'name_pt',
			'name_uk',
			'ref',
			'ref_cols',
			'ref_rows',
			'tunnel',
		],
	},
	street_labels_points: {
		minzoom: 12,
		maxzoom: 14,
		fields: [
			'kind',
			'name',
			'name_ar',
			'name_de',
			'name_el',
			'name_en',
			'name_es',
			'name_fr',
			'name_it',
			'name_nl',
			'name_pl',
			'name_pt',
			'name_uk',
			'ref',
		],
	},
	street_polygons: { minzoom: 11, maxzoom: 14, fields: ['bridge', 'kind', 'rail', 'service', 'surface', 'tunnel'] },
	streets: {
		minzoom: 5,
		maxzoom: 14,
		fields: [
			'bicycle',
			'bridge',
			'horse',
			'kind',
			'link',
			'oneway',
			'oneway_reverse',
			'rail',
			'service',
			'surface',
			'tracktype',
			'tunnel',
		],
	},
	streets_polygons_labels: {
		minzoom: 14,
		maxzoom: 14,
		fields: [
			'kind',
			'name',
			'name_ar',
			'name_de',
			'name_el',
			'name_en',
			'name_es',
			'name_fr',
			'name_it',
			'name_nl',
			'name_pl',
			'name_pt',
			'name_uk',
		],
	},
	water_lines: { minzoom: 9, maxzoom: 14, fields: ['bridge', 'kind', 'tunnel'] },
	water_lines_labels: {
		minzoom: 12,
		maxzoom: 14,
		fields: [
			'bridge',
			'kind',
			'name',
			'name_ar',
			'name_de',
			'name_el',
			'name_en',
			'name_es',
			'name_fr',
			'name_it',
			'name_nl',
			'name_pl',
			'name_pt',
			'name_uk',
			'tunnel',
		],
	},
	water_polygons: { minzoom: 0, maxzoom: 14, fields: ['kind', 'way_area'] },
	water_polygons_labels: {
		minzoom: 4,
		maxzoom: 14,
		fields: [
			'kind',
			'name',
			'name_ar',
			'name_de',
			'name_el',
			'name_en',
			'name_es',
			'name_fr',
			'name_it',
			'name_nl',
			'name_pl',
			'name_pt',
			'name_uk',
			'way_area',
		],
	},
};
